// Auto-generated by tools/generate_worker_protocol.mjs. Do not edit by hand.

import { WORKER_COMMANDS, WORKER_EVENTS, COMMAND_FIELDS, EVENT_FIELDS } from './protocol.gen.mjs';

const COMMAND_SET = new Set(WORKER_COMMANDS);
const EVENT_SET = new Set(WORKER_EVENTS);

function assertPayloadFields(label, payload, required) {
  if (!required || !required.length) return;
  const missing = [];
  for (const key of required) {
    if (!Object.prototype.hasOwnProperty.call(payload, key)) missing.push(key);
  }
  if (missing.length) {
    throw new Error(`${label} missing fields: ${missing.join(', ')}`);
  }
}

export function encodeCommand(cmd, payload = {}) {
  if (!COMMAND_SET.has(cmd)) {
    throw new Error('Unknown command: ' + cmd);
  }
  if (payload == null || typeof payload !== "object") {
    return { cmd };
  }
  const required = COMMAND_FIELDS?.[cmd]?.required || [];
  assertPayloadFields(`Command ${cmd}`, payload, required);
  return { cmd, ...payload };
}

export function decodeCommand(message) {
  if (!message || typeof message !== "object") {
    throw new Error('Command message must be an object');
  }
  const cmd = message.cmd;
  if (typeof cmd !== "string" || !COMMAND_SET.has(cmd)) {
    throw new Error('Unknown command: ' + String(cmd));
  }
  const payload = { ...message };
  delete payload.cmd;
  return { cmd, payload };
}

export function dispatchCommand(handlers, message) {
  const decoded = decodeCommand(message);
  const required = COMMAND_FIELDS?.[decoded.cmd]?.required || [];
  assertPayloadFields(`Command ${decoded.cmd}`, decoded.payload, required);
  const handler = handlers?.[decoded.cmd];
  if (typeof handler !== "function") {
    throw new Error('Unhandled command: ' + decoded.cmd);
  }
  return handler(decoded.payload, message);
}

export function encodeEvent(kind, payload = {}) {
  if (!EVENT_SET.has(kind)) {
    throw new Error('Unknown event: ' + kind);
  }
  if (payload == null || typeof payload !== "object") {
    return { kind };
  }
  const required = EVENT_FIELDS?.[kind]?.required || [];
  assertPayloadFields(`Event ${kind}`, payload, required);
  return { kind, ...payload };
}

export function decodeEvent(message) {
  if (!message || typeof message !== "object") {
    throw new Error('Event message must be an object');
  }
  const kind = message.kind;
  if (typeof kind !== "string" || !EVENT_SET.has(kind)) {
    throw new Error('Unknown event: ' + String(kind));
  }
  const payload = { ...message };
  delete payload.kind;
  return { kind, payload };
}

export function dispatchEvent(handlers, message) {
  const decoded = decodeEvent(message);
  const required = EVENT_FIELDS?.[decoded.kind]?.required || [];
  assertPayloadFields(`Event ${decoded.kind}`, decoded.payload, required);
  const handler = handlers?.[decoded.kind];
  if (typeof handler !== "function") {
    throw new Error('Unhandled event: ' + decoded.kind);
  }
  return handler(decoded.payload, message);
}
