// Auto-generated by tools/generate_worker_protocol.mjs. Do not edit by hand.

export const SNAPSHOT_VIEW_FIELDS = [
  [Float64Array, ["xpos","xmat","gsize","qpos","bxpos","bxmat","jnt_range"]],
  [Float32Array, ["scn_pos","scn_mat","scn_size","scn_rgba","flexvert_xpos","light_xpos","light_xdir"]],
  [Int32Array, ["scn_type","scn_matid","scn_dataid","scn_objtype","scn_objid","scn_category","scn_geomorder","gtype","geom_bodyid","body_parentid","body_jntadr","body_jntnum","jtype","jnt_qposadr","eq_type","eq_obj1id","eq_obj2id","eq_objtype"]],
  [Uint8Array, ["scn_label","eq_active"]],
];

export const GEOM_VIEW_FIELDS_OPTIONAL = [
  [Float64Array, ["bxpos","bxmat","qpos"]],
  [Float32Array, ["scn_pos","scn_mat","scn_size","scn_rgba","flexvert_xpos","light_xpos","light_xdir"]],
  [Int32Array, ["scn_type","scn_matid","scn_dataid","scn_objtype","scn_objid","scn_category","scn_geomorder","eq_type","eq_obj1id","eq_obj2id","eq_objtype"]],
  [Uint8Array, ["scn_label","eq_active"]],
];

export const GEOM_VIEW_FIELDS_ALWAYS = [
  [Float64Array, ["gsize"]],
  [Int32Array, ["gtype"]],
];

export const WORKER_COMMANDS = [
  "strictReport",
  "load",
  "snapshot",
  "setPaused",
  "setRate",
  "setSnapshotHz",
  "setCameraMode",
  "setField",
  "setLabelMode",
  "setFrameMode",
  "setVisualOption",
  "setVoptFlag",
  "setSceneFlag",
  "setGroupState",
  "setCtrl",
  "setQpos",
  "setEqualityActive",
  "historyScrub",
  "historyConfig",
  "keyframeSelect",
  "keyframeSave",
  "keyframeLoad",
  "setWatch",
  "step",
  "reset",
  "gesture",
  "align",
  "copyState",
  "applyPerturb",
  "setSelection",
  "selectAt",
  "setCtrlNoise"
];

export const WORKER_EVENTS = [
  "strict_report",
  "run_state",
  "ready",
  "struct_state",
  "meta_cameras",
  "meta_geoms",
  "meta_joints",
  "meta",
  "snapshot",
  "keyframes",
  "history",
  "watch",
  "render_assets",
  "gesture",
  "align",
  "copyState",
  "options",
  "selection",
  "latency_probe",
  "log",
  "error"
];

export const COMMAND_FIELDS = {
  "strictReport": { required: ["id"], optional: [] },
  "load": { required: ["xmlText"], optional: [] },
  "snapshot": { required: [], optional: [] },
  "setPaused": { required: ["paused"], optional: [] },
  "setRate": { required: ["rate"], optional: [] },
  "setSnapshotHz": { required: ["hz"], optional: [] },
  "setCameraMode": { required: ["mode"], optional: [] },
  "setField": { required: ["target","path","kind","value"], optional: [] },
  "setLabelMode": { required: ["mode"], optional: [] },
  "setFrameMode": { required: ["mode"], optional: [] },
  "setVisualOption": { required: ["field","value"], optional: [] },
  "setVoptFlag": { required: ["index","enabled"], optional: [] },
  "setSceneFlag": { required: ["index","enabled"], optional: [] },
  "setGroupState": { required: ["group","index","enabled"], optional: [] },
  "setCtrl": { required: ["index","value"], optional: [] },
  "setQpos": { required: ["index","value"], optional: [] },
  "setEqualityActive": { required: ["index","active"], optional: [] },
  "historyScrub": { required: ["offset"], optional: [] },
  "historyConfig": { required: ["captureHz","capacity"], optional: [] },
  "keyframeSelect": { required: ["index"], optional: [] },
  "keyframeSave": { required: ["index"], optional: [] },
  "keyframeLoad": { required: ["index"], optional: [] },
  "setWatch": { required: ["field","index"], optional: [] },
  "step": { required: ["n"], optional: [] },
  "reset": { required: [], optional: [] },
  "gesture": { required: ["gesture"], optional: [] },
  "align": { required: [], optional: [] },
  "copyState": { required: [], optional: [] },
  "applyPerturb": { required: ["phase"], optional: [] },
  "setSelection": { required: ["bodyId"], optional: ["localpos"] },
  "selectAt": { required: ["relx","rely","aspect"], optional: [] },
  "setCtrlNoise": { required: ["std","rate"], optional: [] },
};

export const EVENT_FIELDS = {
  "strict_report": { required: ["id","report"], optional: [] },
  "run_state": { required: ["running"], optional: [] },
  "ready": { required: ["abi","dt","ngeom","optionSupport","visual","statistic"], optional: [] },
  "struct_state": { required: ["scope","value"], optional: [] },
  "meta_cameras": { required: ["cameras"], optional: [] },
  "meta_geoms": { required: ["geoms"], optional: [] },
  "meta_joints": { required: ["ngeom","nbody","njnt","geom_bodyid","body_jntadr","body_jntnum","body_parentid","jtype","jnt_qposadr","jnt_range","jnt_names"], optional: [] },
  "meta": { required: ["actuators"], optional: [] },
  "snapshot": { required: ["tSim","ngeom","scn_ngeom","nq","nv","nbody","xpos","xmat","bxpos","bxmat","gesture","drag","viewerCamera","voptFlags","sceneFlags","labelMode","frameMode","cameraMode","frameId","optionSupport","paused","pausedSource","rate","measuredSlowdown","qpos","options","history","keyframes","watchSources"], optional: [] },
  "keyframes": { required: ["capacity","count","labels","slots","lastSaved","lastLoaded","keyIndex"], optional: [] },
  "history": { required: ["captureHz","capacity","count","horizon","scrubIndex","live"], optional: [] },
  "watch": { required: ["field","index","status","valid","summary"], optional: [] },
  "render_assets": { required: ["assets"], optional: [] },
  "gesture": { required: ["gesture","drag"], optional: [] },
  "align": { required: ["seq","center","radius","timestamp"], optional: [] },
  "copyState": { required: ["seq","precision","nq","nv","timestamp","complete"], optional: [] },
  "options": { required: ["voptFlags","sceneFlags","labelMode","frameMode","cameraMode","groups","options"], optional: [] },
  "selection": { required: ["seq","bodyId","geomId","flexId","skinId","point","localpos","timestamp"], optional: [] },
  "latency_probe": { required: ["sentWallMs"], optional: ["frameId"] },
  "log": { required: ["message"], optional: [] },
  "error": { required: ["message"], optional: [] },
};

export const SNAPSHOT_TRANSFER_FIELDS = [
  "xpos",
  "xmat",
  "gsize",
  "gtype",
  "bxpos",
  "bxmat",
  "qpos",
  "scn_type",
  "scn_pos",
  "scn_mat",
  "scn_size",
  "scn_rgba",
  "scn_matid",
  "scn_dataid",
  "scn_objtype",
  "scn_objid",
  "scn_category",
  "scn_geomorder",
  "scn_label",
  "flexvert_xpos",
  "eq_type",
  "eq_obj1id",
  "eq_obj2id",
  "eq_objtype",
  "eq_active",
  "light_xpos",
  "light_xdir",
  "ctrl"
];

export const CONTACT_TRANSFER_FIELDS = [];

function collectBuffers(source, keys, out, seen) {
  if (!source) return;
  for (const key of keys) {
    const value = source[key];
    if (!value || !ArrayBuffer.isView(value)) continue;
    const buffer = value.buffer;
    if (!(buffer instanceof ArrayBuffer) || seen.has(buffer)) continue;
    seen.add(buffer);
    out.push(buffer);
  }
}

export function collectSnapshotTransfers(payload) {
  const transfers = [];
  const seen = new Set();
  collectBuffers(payload, SNAPSHOT_TRANSFER_FIELDS, transfers, seen);
  if (payload?.contacts) {
    collectBuffers(payload.contacts, CONTACT_TRANSFER_FIELDS, transfers, seen);
  }
  return transfers;
}
