// Auto-generated by tools/generate_worker_protocol.mjs. Do not edit by hand.

import { buildWorkerUrl, isPerfEnabled, perfMarkOnce, perfNow, perfSample, logWarn, logError, logStatus, strictCatch, getStrictReport } from './viewer_runtime.mjs';
import { MJ_GROUP_COUNT, SCENE_FLAG_DEFAULTS } from './viewer_defaults.mjs';
import { VISUAL_FIELD_DESCRIPTORS } from './viewer_structs.mjs';
import { bool, cloneStruct, createDefaultHistoryState, createDefaultKeyframeState, createDefaultWatchState, createViewerGroupState, normaliseGroupState, resolveStructPath, toNumber } from './viewer_shared.mjs';
import { dispatchEvent } from './dispatch.gen.mjs';
import { SNAPSHOT_VIEW_FIELDS, GEOM_VIEW_FIELDS_OPTIONAL, GEOM_VIEW_FIELDS_ALWAYS } from './protocol.gen.mjs';

const ASSET_BASE_URL = new URL('./', import.meta.url);
const WORKER_URL = new URL('physics.worker.mjs', ASSET_BASE_URL);
const MODEL_ALIASES = {
  rkob: 'mujoco_Rajagopal2015_simple.xml',
  raj: 'mujoco_Rajagopal2015_simple.xml',
};
const MODEL_POOL = [
  'mujoco_Rajagopal2015_simple.xml',
];

function applyViewFields(target, source, fields, viewFn, options = {}) {
  const skipMissing = !!options.skipMissing;
  for (const [Ctor, keys] of fields) {
    for (const key of keys) {
      const value = source[key];
      if (skipMissing && value == null) continue;
      target[key] = viewFn(value, Ctor);
    }
  }
}

function applyHistoryPayload(target, payload) {
  const history = target.history || createDefaultHistoryState();
  history.captureHz = Number(payload.captureHz) || 0;
  history.capacity = Math.max(0, Number(payload.capacity) || 0);
  history.count = Math.max(0, Number(payload.count) || 0);
  history.horizon = Number(payload.horizon) || 0;
  history.scrubIndex = Number(payload.scrubIndex) || 0;
  history.live = payload.live !== false;
  target.history = history;
}

function applyKeyframesPayload(target, payload, keyIndexOverride = null) {
  const keyframes = target.keyframes || createDefaultKeyframeState();
  if (typeof payload.capacity === 'number') {
    keyframes.capacity = payload.capacity | 0;
  }
  if (typeof payload.count === 'number') {
    keyframes.count = Math.max(0, payload.count | 0);
  }
  if (Array.isArray(payload.labels)) {
    keyframes.labels = payload.labels.slice();
  }
  if (Array.isArray(payload.slots)) {
    keyframes.slots = payload.slots.map((slot) => ({
      index: Number(slot.index) || 0,
      label: typeof slot.label === 'string' ? slot.label : `Key ${slot.index | 0}`,
      kind: slot.kind || 'user',
      available: !!slot.available,
    }));
  }
  if (typeof payload.lastSaved === 'number') {
    keyframes.lastSaved = payload.lastSaved | 0;
  }
  if (typeof payload.lastLoaded === 'number') {
    keyframes.lastLoaded = payload.lastLoaded | 0;
  }
  target.keyframes = keyframes;
  const keyIndex = Number.isFinite(keyIndexOverride)
    ? keyIndexOverride
    : (Number.isFinite(payload.keyIndex) ? payload.keyIndex : null);
  if (keyIndex != null) {
    target.keyIndex = keyIndex | 0;
  }
}

function applyWatchPayload(target, payload, options = {}) {
  const watch = target.watch || createDefaultWatchState();
  if (typeof payload.field === 'string') {
    watch.field = payload.field;
  }
  const indexIsFinite = Number.isFinite(payload.index);
  if (typeof payload.index === 'number' && (!options.requireFiniteIndex || indexIsFinite)) {
    watch.index = payload.index | 0;
  }
  if ('value' in payload) {
    const raw = Number(payload.value);
    watch.value = Number.isFinite(raw) ? raw : null;
  }
  const minVal = Number(payload.min);
  const maxVal = Number(payload.max);
  watch.min = Number.isFinite(minVal) ? minVal : null;
  watch.max = Number.isFinite(maxVal) ? maxVal : null;
  const samples = Number(payload.samples) || 0;
  watch.samples = options.clampSamples ? Math.max(0, samples) : samples;
  watch.status = payload.status || watch.status || 'idle';
  watch.valid = !!payload.valid;
  if (options.computeSummary) {
    if (watch.valid && typeof watch.value === 'number') {
      watch.summary = watch.value.toPrecision(6);
    } else {
      watch.summary = '—';
    }
  } else {
    const summary = typeof payload.summary === 'string' ? payload.summary : '';
    watch.summary = summary || watch.summary || '';
  }
  target.watch = watch;
}

function resolveModelFileName(raw) {
  if (raw === null || raw === undefined) return null;
  const token = String(raw).trim();
  if (!token) return null;
  const key = token.toLowerCase();
  const alias = MODEL_ALIASES[key];
  let file = alias || token;
  if (!file.toLowerCase().endsWith('.xml')) {
    file = `${file}.xml`;
  }
  return file;
}

function buildModelCandidates(modelToken, modelFile) {
  const out = [];
  const seen = new Set();
  const pushCandidate = (file, label) => {
    if (!file || seen.has(file)) return;
    seen.add(file);
    out.push({ file, label: label || file });
  };
  if (modelFile) {
    pushCandidate(modelFile, modelToken || modelFile);
  }
  for (const file of MODEL_POOL) {
    pushCandidate(file, file);
  }
  return out;
}


function createInitialSnapshot() {
  return {
    t: 0,
    rate: 1,
    measuredSlowdown: 1,
    paused: false,
    ngeom: 0,
    nq: 0,
    nv: 0,
    pausedSource: 'backend',
    rateSource: 'backend',
    gesture: { mode: 'idle', phase: 'idle', pointer: null },
    drag: { dx: 0, dy: 0 },
    voptFlags: Array.from({ length: 32 }, () => 0),
    sceneFlags: SCENE_FLAG_DEFAULTS.map((flag) => (flag ? 1 : 0)),
    labelMode: 0,
    frameMode: 0,
    cameraMode: 0,
    viewerCamera: null,
    groups: createViewerGroupState(true),
    align: null,
    copyState: null,
    selection: null,
    xpos: new Float64Array(0),
    xmat: new Float64Array(0),
    gsize: null,
    gtype: null,
    contacts: null,
    renderAssets: null,
    options: null,
    ctrl: null,
    optionSupport: { supported: false, pointers: [] },
    visual: null,
    statistic: null,
    visualDefaults: null,
    visualVersion: 0,
    visualDefaultsVersion: 0,
    statisticVersion: 0,
    cameras: [],
    history: createDefaultHistoryState(),
    keyframes: createDefaultKeyframeState(),
    watch: createDefaultWatchState(),
    keyIndex: -1,
  };
}

function resolveSnapshot(state) {
  const viewOrNull = (value, Ctor) => {
    if (ArrayBuffer.isView(value)) return value;
    if (Array.isArray(value) && Ctor) {
      try {
        return new Ctor(value);
      } catch (err) {
        strictCatch(err, 'backend:view_or_null');
        return null;
      }
    }
    return null;
  };

  const snapshot = {
    t: state.t ?? 0,
    rate: state.rate ?? 1,
    measuredSlowdown: state.measuredSlowdown ?? 1,
    paused: !!state.paused,
    ngeom: state.ngeom ?? 0,
    nq: state.nq ?? 0,
    nv: state.nv ?? 0,
    pausedSource: state.pausedSource ?? 'backend',
    rateSource: state.rateSource ?? 'backend',
    gesture: state.gesture
      ? {
          mode: state.gesture.mode ?? 'idle',
          phase: state.gesture.phase ?? 'idle',
          pointer: state.gesture.pointer
            ? {
                x: Number(state.gesture.pointer.x) || 0,
                y: Number(state.gesture.pointer.y) || 0,
                dx: Number(state.gesture.pointer.dx) || 0,
                dy: Number(state.gesture.pointer.dy) || 0,
                buttons: Number(state.gesture.pointer.buttons ?? 0),
                pressure: Number(state.gesture.pointer.pressure ?? 0),
              }
            : null,
        }
      : { mode: 'idle', phase: 'idle', pointer: null },
    drag: state.drag
      ? {
          dx: Number(state.drag.dx) || 0,
          dy: Number(state.drag.dy) || 0,
        }
      : { dx: 0, dy: 0 },
    selection: state.selection && typeof state.selection === 'object'
      ? {
          seq: Number(state.selection.seq) || 0,
          bodyId: Number(state.selection.bodyId) | 0,
          geomId: Number(state.selection.geomId) | 0,
          flexId: Number(state.selection.flexId) | 0,
          skinId: Number(state.selection.skinId) | 0,
          point: Array.isArray(state.selection.point)
            ? [Number(state.selection.point[0]) || 0, Number(state.selection.point[1]) || 0, Number(state.selection.point[2]) || 0]
            : [0, 0, 0],
          localpos: Array.isArray(state.selection.localpos)
            ? [Number(state.selection.localpos[0]) || 0, Number(state.selection.localpos[1]) || 0, Number(state.selection.localpos[2]) || 0]
            : [0, 0, 0],
          timestamp: Number(state.selection.timestamp) || 0,
        }
      : null,
    voptFlags: Array.isArray(state.voptFlags)
      ? state.voptFlags.map((flag) => (flag ? 1 : 0))
      : Array.from({ length: 32 }, () => 0),
    sceneFlags: (() => {
      const flags = [];
      const source = Array.isArray(state.sceneFlags) ? state.sceneFlags : [];
      for (let i = 0; i < SCENE_FLAG_DEFAULTS.length; i += 1) {
        if (i < source.length && source[i] != null) {
          flags[i] = source[i] ? 1 : 0;
        } else {
          flags[i] = SCENE_FLAG_DEFAULTS[i] ? 1 : 0;
        }
      }
      return flags;
    })(),
    labelMode: Number.isFinite(state.labelMode) ? (state.labelMode | 0) : 0,
    frameMode: Number.isFinite(state.frameMode) ? (state.frameMode | 0) : 0,
    cameraMode: Number.isFinite(state.cameraMode) ? (state.cameraMode | 0) : 0,
    viewerCamera:
      state.viewerCamera && typeof state.viewerCamera === 'object'
        ? {
            type: Number.isFinite(state.viewerCamera.type) ? (state.viewerCamera.type | 0) : 0,
            lookat: Array.isArray(state.viewerCamera.lookat)
              ? state.viewerCamera.lookat.slice(0, 3).map((n) => Number(n) || 0)
              : [0, 0, 0],
            distance: Number(state.viewerCamera.distance) || 0,
            azimuth: Number(state.viewerCamera.azimuth) || 0,
            elevation: Number(state.viewerCamera.elevation) || 0,
            orthographic: !!state.viewerCamera.orthographic,
          }
        : null,
    actuators: Array.isArray(state.actuators) ? state.actuators.slice() : null,
    options: state.options ?? null,
    ctrl: state.ctrl ? Array.from(state.ctrl) : null,
    cameras: Array.isArray(state.cameras) ? state.cameras.slice() : null,
    geoms: Array.isArray(state.geoms) ? state.geoms.slice() : null,
    frameId: Number.isFinite(state.frameId) ? (state.frameId | 0) : null,
    optionSupport: state.optionSupport ? { ...state.optionSupport } : null,
    info: state.info ? { ...state.info } : null,
    visual: cloneStruct(state.visual),
    statistic: cloneStruct(state.statistic),
    visualDefaults: cloneStruct(state.visualDefaults),
    visualVersion: Number.isFinite(state.visualVersion) ? (state.visualVersion | 0) : 0,
    visualDefaultsVersion: Number.isFinite(state.visualDefaultsVersion) ? (state.visualDefaultsVersion | 0) : 0,
    statisticVersion: Number.isFinite(state.statisticVersion) ? (state.statisticVersion | 0) : 0,
    scn_ngeom: Number.isFinite(state.scn_ngeom) ? (state.scn_ngeom | 0) : 0,
    nisland: typeof state.nisland === 'number' ? (state.nisland | 0) : 0,
    jnt_names: Array.isArray(state.jnt_names) ? state.jnt_names.slice() : null,
    eq_names: Array.isArray(state.eq_names) ? state.eq_names.slice() : null,
    contacts:
      state.contacts && typeof state.contacts === 'object'
        ? {
            ...state.contacts,
            pos: viewOrNull(state.contacts.pos, Float64Array),
            frame: viewOrNull(state.contacts.frame, Float64Array),
            geom1: viewOrNull(state.contacts.geom1, Int32Array),
            geom2: viewOrNull(state.contacts.geom2, Int32Array),
            dist: viewOrNull(state.contacts.dist, Float64Array),
            fric: viewOrNull(state.contacts.fric, Float64Array),
            force: viewOrNull(state.contacts.force, Float64Array),
          }
        : null,
    align: state.align
      ? {
          seq: Number(state.align.seq) || 0,
          center: Array.isArray(state.align.center)
            ? state.align.center.slice(0, 3).map((n) => Number(n) || 0)
            : [0, 0, 0],
          radius: Number(state.align.radius) || 0,
          source: state.align.source || 'backend',
          timestamp: Number(state.align.timestamp) || 0,
        }
      : null,
    copyState: state.copyState
      ? {
          seq: Number(state.copyState.seq) || 0,
          precision: state.copyState.precision || 'standard',
          nq: Number(state.copyState.nq) || 0,
          nv: Number(state.copyState.nv) || 0,
          timestamp: Number(state.copyState.timestamp) || 0,
          complete: !!state.copyState.complete,
          qposPreview: Array.isArray(state.copyState.qposPreview)
            ? state.copyState.qposPreview.map((n) => Number(n) || 0)
            : [],
          qvelPreview: Array.isArray(state.copyState.qvelPreview)
            ? state.copyState.qvelPreview.map((n) => Number(n) || 0)
            : [],
        }
      : null,
    renderAssets: state.renderAssets ?? null,
    groups: state.groups ? normaliseGroupState(state.groups) : null,
    nbody: Number.isFinite(state.nbody) ? (state.nbody | 0) : null,
    njnt: Number.isFinite(state.njnt) ? (state.njnt | 0) : null,
    history: state.history
      ? {
          captureHz: Number(state.history.captureHz) || 0,
          capacity: Number(state.history.capacity) || 0,
          count: Number(state.history.count) || 0,
          horizon: Number(state.history.horizon) || 0,
          scrubIndex: Number(state.history.scrubIndex) || 0,
          live: state.history.live !== false,
        }
      : null,
    keyframes: state.keyframes
      ? {
          capacity: Number(state.keyframes.capacity) || 0,
          count: Number(state.keyframes.count) || 0,
          labels: Array.isArray(state.keyframes.labels) ? state.keyframes.labels.slice() : [],
          slots: Array.isArray(state.keyframes.slots) ? state.keyframes.slots.map((slot) => ({ ...slot })) : [],
          lastSaved: Number.isFinite(state.keyframes.lastSaved) ? (state.keyframes.lastSaved | 0) : -1,
          lastLoaded: Number.isFinite(state.keyframes.lastLoaded) ? (state.keyframes.lastLoaded | 0) : -1,
        }
      : null,
    watch: state.watch
      ? {
          field: state.watch.field || 'qpos',
          index: Number.isFinite(state.watch.index) ? (state.watch.index | 0) : 0,
          value: typeof state.watch.value === 'number' && Number.isFinite(state.watch.value) ? state.watch.value : null,
          min: typeof state.watch.min === 'number' && Number.isFinite(state.watch.min) ? state.watch.min : null,
          max: typeof state.watch.max === 'number' && Number.isFinite(state.watch.max) ? state.watch.max : null,
          samples: Number(state.watch.samples) || 0,
          summary: state.watch.summary || '',
          status: state.watch.status || 'idle',
          valid: !!state.watch.valid,
          sources: state.watch.sources ? { ...state.watch.sources } : {},
        }
      : null,
  };
  applyViewFields(snapshot, state, SNAPSHOT_VIEW_FIELDS, viewOrNull);
  return snapshot;
}


export async function createBackend(options = {}) {
  const perfEnabled = isPerfEnabled();
  const snapshotDebug =
    typeof window !== 'undefined'
    && (
      (window.location?.search?.includes('snapshot=1'))
      || (window.location?.search?.includes('snapshot=debug'))
    );
  if (typeof window !== 'undefined') {
    window.PLAY_SNAPSHOT_DEBUG = snapshotDebug;
  }
  const modelToken = typeof options.model === 'string' ? options.model.trim() : '';
  const modelFile = resolveModelFileName(modelToken);
  const modelCandidates = buildModelCandidates(modelToken, modelFile);
  const initialCandidate = modelCandidates[0] || null;
  const initialModelInfo = {
    token: modelToken || '',
    file: initialCandidate ? initialCandidate.file : null,
    label: initialCandidate ? initialCandidate.label : (modelToken || ''),
  };
  const listeners = new Set();
  const normaliseInt = (value, fallback = 0) => {
    const num = Number(value);
    return Number.isFinite(num) ? (num | 0) : fallback;
  };
  let client = null;
  const kind = 'worker';
  let lastSnapshot = createInitialSnapshot();
  let lastFrameId = -1;
  let messageHandler = null;
  let lastXmlText = null;
  let strictRequestSeq = 0;
  const strictRequests = new Map();

  function applySimulateMaskBinding(binding, value, prefix, field, invert, warnLabel) {
    if (!binding || !binding.startsWith(`${prefix}[`)) return false;
    const start = prefix.length + 1;
    const end = binding.indexOf(']', start);
    const bitIndex = end > start ? normaliseInt(binding.slice(start, end), -1) : -1;
    if (bitIndex >= 0 && bitIndex < 32) {
      const active = bool(value);
      const bit = 1 << bitIndex;
      const currentMask =
        typeof lastSnapshot.options?.[field] === 'number'
          ? (lastSnapshot.options[field] | 0)
          : 0;
      const nextMask = invert
        ? (active ? (currentMask & ~bit) : (currentMask | bit))
        : (active ? (currentMask | bit) : (currentMask & ~bit));
      try {
        client.postMessage?.({
          cmd: 'setField',
          target: 'mjOption',
          path: [field],
          kind: 'int',
          size: 1,
          value: [nextMask],
        });
      } catch (err) {
        logWarn(`[backend ${warnLabel}] post failed`, err);
        strictCatch(err, `backend:setField:${warnLabel}`);
        throw err;
      }
    }
    return true;
  }

  function spawnWorkerBackend() {
    const workerUrl = buildWorkerUrl(WORKER_URL);
    return new Worker(workerUrl, { type: 'module' });
  }

  async function requestWorkerStrictReport() {
    if (!client || typeof client.postMessage !== 'function') return null;
    const id = (strictRequestSeq += 1);
    const promise = new Promise((resolve, reject) => {
      strictRequests.set(id, { resolve, reject });
    });
    try {
      client.postMessage({ cmd: 'strictReport', id });
    } catch (err) {
      strictRequests.delete(id);
      strictCatch(err, 'backend:strict_report_request');
      throw err;
    }
    return promise;
  }

  async function loadDefaultXml() {
    const errors = [];
    if (!modelCandidates.length) {
      throw new Error('No model loaded. No model candidates available.');
    }
    for (const candidate of modelCandidates) {
      const file = candidate.file;
      if (!file) continue;
    try {
      const url = new URL(file, ASSET_BASE_URL);
      const res = await fetch(url, { cache: 'no-store' });
      if (!res.ok) {
        errors.push(`fetch ${file} status ${res.status}`);
        logWarn(`[backend] fetch ${file} failed with status ${res.status}`);
        continue;
      }
      const text = await res.text();
      if (text && text.trim().length > 0) {
        return text;
      }
      errors.push(`empty content for ${file}`);
    } catch (err) {
      errors.push(`fetch ${file} error ${String(err)}`);
      logWarn('[backend] failed to fetch xml', { file, err });
      strictCatch(err, 'backend:fetch_xml');
    }
  }
    throw new Error(
      `No model loaded. Tried: ${modelCandidates.map((c) => c.file).join(', ')}. Errors: ${errors.join('; ')}`,
    );
  }

  function notifyListeners() {
    if (!Number.isFinite(lastSnapshot.rate)) {
      lastSnapshot.rate = 1;
    }
    if (typeof lastSnapshot.paused !== 'boolean') {
      lastSnapshot.paused = false;
    }
    if (!lastSnapshot.rateSource) lastSnapshot.rateSource = 'backend';
    if (!lastSnapshot.pausedSource) lastSnapshot.pausedSource = 'backend';
    const snapshot = resolveSnapshot(lastSnapshot);
    for (const fn of listeners) {
      try {
        fn(snapshot);
      } catch (err) {
        logError(err);
        strictCatch(err, 'backend:listener');
      }
    }
    return snapshot;
  }

  function detachClient() {
    if (messageHandler) {
      try { client?.removeEventListener?.('message', messageHandler); } catch (err) { strictCatch(err, 'backend:detach_listener'); }
      try { if (client && 'onmessage' in client) client.onmessage = null; } catch (err) { strictCatch(err, 'backend:detach_onmessage'); }
    }
  }

  async function restartWorkerWithXml(xmlText) {
    const payload = typeof xmlText === 'string' ? xmlText : String(xmlText ?? '');
    if (!payload || payload.trim().length === 0) {
      return resolveSnapshot(lastSnapshot);
    }
    // Tear down old worker (if any).
    try { detachClient(); } catch (err) { strictCatch(err, 'backend:detach_client'); }
    try { client?.terminate?.(); } catch (err) { strictCatch(err, 'backend:terminate'); }
    client = null;
    // Spawn a fresh worker (new wasm instance).
    try {
      client = await spawnWorkerBackend();
    } catch (err) {
      logError('[backend] worker init failed', err);
      strictCatch(err, 'backend:worker_init');
      throw err;
    }
    // Attach message handler to the new worker.
    if (typeof client.addEventListener === 'function') {
      messageHandler = (evt) => handleMessage(evt);
      client.addEventListener('message', messageHandler);
    } else if ('onmessage' in client) {
      messageHandler = (evt) => handleMessage(evt);
      client.onmessage = messageHandler;
    }
    const loadRate = Number.isFinite(lastSnapshot.rate) ? lastSnapshot.rate : 1;
    // Reset local snapshot state and kick off load on the fresh worker.
    lastSnapshot = createInitialSnapshot();
    lastFrameId = -1;
    lastSnapshot.visualDefaults = null;
    notifyListeners();
    try {
      client.postMessage({ cmd: 'load', rate: loadRate, xmlText: payload });
      client.postMessage({ cmd: 'snapshot' });
    } catch (err) {
      logError('[backend load] failed', err);
      strictCatch(err, 'backend:load');
      throw err;
    }
    return resolveSnapshot(lastSnapshot);
  }

  function formatCopyNumber(value, precision) {
    const num = Number(value);
    if (!Number.isFinite(num)) return '0';
    if (precision === 'full') {
      return num.toPrecision(16);
    }
    return num.toPrecision(6);
  }

  function buildCopyKeyXmlFromPayload(data) {
    if (!data || typeof data !== 'object') return null;
    const precision = data.precision === 'full' ? 'full' : 'standard';
    const nq = Number(data.nq) || 0;
    const nv = Number(data.nv) || 0;
    const nu = Number(data.nu) || 0;
    const na = Number(data.na) || 0;
    const nmocap = Number(data.nmocap) || 0;
    const tSim = typeof data.tSim === 'number' ? data.tSim : 0;
    const hasFullQpos = Array.isArray(data.qpos) && data.qpos.length >= nq && nq > 0;
    const hasFullQvel = Array.isArray(data.qvel) && data.qvel.length >= nv && nv > 0;
    const hasFullCtrl = Array.isArray(data.ctrl) && data.ctrl.length >= nu && nu > 0;
    const hasFullAct = Array.isArray(data.act) && data.act.length >= na && na > 0;
    const hasFullMpos = Array.isArray(data.mpos) && data.mpos.length >= nmocap * 3 && nmocap > 0;
    const hasFullMquat = Array.isArray(data.mquat) && data.mquat.length >= nmocap * 4 && nmocap > 0;
    const qpos = hasFullQpos
      ? data.qpos
      : (Array.isArray(data.qposPreview) ? data.qposPreview : []);
    const qvel = hasFullQvel
      ? data.qvel
      : (Array.isArray(data.qvelPreview) ? data.qvelPreview : []);
    const ctrl = hasFullCtrl
      ? data.ctrl
      : (Array.isArray(data.ctrlPreview) ? data.ctrlPreview : []);
    const act = hasFullAct ? data.act : [];
    const mpos = hasFullMpos ? data.mpos : [];
    const mquat = hasFullMquat ? data.mquat : [];
    const format = (v) => formatCopyNumber(v, precision);
    let xml = '<key\n';
    xml += `  time=\"${format(tSim)}\"\n`;
    if (qpos.length) {
      xml += `  qpos=\"${qpos.map(format).join(' ')}\"\n`;
    }
    if (qvel.length) {
      xml += `  qvel=\"${qvel.map(format).join(' ')}\"\n`;
    }
    if (act.length) {
      xml += `  act=\"${act.map(format).join(' ')}\"\n`;
    }
    if (ctrl.length) {
      xml += `  ctrl=\"${ctrl.map(format).join(' ')}\"\n`;
    }
    if (mpos.length) {
      xml += `  mpos=\"${mpos.map(format).join(' ')}\"\n`;
    }
    if (mquat.length) {
      xml += `  mquat=\"${mquat.map(format).join(' ')}\"\n`;
    }
    xml += '/>';
    return xml;
  }

  async function writeCopyKeyToClipboard(xml) {
    if (!xml) return;
    if (typeof navigator === 'undefined' || !navigator.clipboard || typeof navigator.clipboard.writeText !== 'function') {
      logWarn('[backend copyState] clipboard API unavailable');
      return;
    }
    try {
      await navigator.clipboard.writeText(xml);
    } catch (err) {
      logError('[backend copyState] clipboard write failed', err);
      strictCatch(err, 'backend:clipboard_write');
      throw err;
    }
  }

  function applyOptionSnapshot(data) {
    if (!data || typeof data !== 'object') return;
    if (Array.isArray(data.voptFlags)) {
      lastSnapshot.voptFlags = data.voptFlags.map((flag) => (flag ? 1 : 0));
    }
    if (Array.isArray(data.sceneFlags)) {
      const flags = [];
      for (let i = 0; i < SCENE_FLAG_DEFAULTS.length; i += 1) {
        if (i < data.sceneFlags.length && data.sceneFlags[i] != null) {
          flags[i] = data.sceneFlags[i] ? 1 : 0;
        } else {
          flags[i] = SCENE_FLAG_DEFAULTS[i] ? 1 : 0;
        }
      }
      lastSnapshot.sceneFlags = flags;
    }
    if (typeof data.labelMode === 'number' && Number.isFinite(data.labelMode)) {
      lastSnapshot.labelMode = data.labelMode | 0;
    }
    if (typeof data.frameMode === 'number' && Number.isFinite(data.frameMode)) {
      lastSnapshot.frameMode = data.frameMode | 0;
    }
    if (typeof data.cameraMode === 'number' && Number.isFinite(data.cameraMode)) {
      lastSnapshot.cameraMode = data.cameraMode | 0;
    }
    if (data.groups && typeof data.groups === 'object') {
      lastSnapshot.groups = normaliseGroupState(data.groups);
    }
    if (data.options) {
      lastSnapshot.options = data.options;
    }
  }

  function setRunState(run, source = 'ui', notifyBackend = true) {
    const nextPaused = !run;
    if (notifyBackend) {
      try {
        client.postMessage?.({ cmd: 'setPaused', paused: nextPaused, source });
      } catch (err) {
        logWarn('[backend] setPaused post failed', err);
        strictCatch(err, 'backend:setPaused');
      }
    }
    return resolveSnapshot(lastSnapshot);
  }

  function setRate(nextRate, source = 'ui') {
    const raw = Number(nextRate);
    const clamped = Number.isFinite(raw) ? Math.max(0.0625, Math.min(16, raw)) : 1;
    try {
      client.postMessage?.({ cmd: 'setRate', rate: clamped, source });
    } catch (err) {
      logWarn('[backend] setRate post failed', err);
      strictCatch(err, 'backend:setRate');
    }
    return resolveSnapshot(lastSnapshot);
  }

  async function loadXmlText(xmlText) {
    const payload = typeof xmlText === 'string' ? xmlText : String(xmlText ?? '');
    lastXmlText = payload;
    return restartWorkerWithXml(payload);
  }

  function applyVisualStatePayload(payload) {
    if (!payload || typeof client?.postMessage !== 'function') {
      return resolveSnapshot(lastSnapshot);
    }
    if (payload.visual && typeof payload.visual === 'object') {
      for (const descriptor of VISUAL_FIELD_DESCRIPTORS) {
        const value = resolveStructPath(payload.visual, descriptor.path);
        if (value == null) continue;
        try {
          client.postMessage({
            cmd: 'setField',
            target: 'mjVisual',
            path: descriptor.path,
            kind: descriptor.kind,
            size: descriptor.size,
            value,
          });
        } catch (err) {
          logWarn('[backend setField] failed', descriptor.path, err);
          strictCatch(err, 'backend:setField_descriptor');
        }
      }
    }
    if (Array.isArray(payload.sceneFlags)) {
      for (let i = 0; i < payload.sceneFlags.length; i += 1) {
        const enabled = !!payload.sceneFlags[i];
        try {
          client.postMessage?.({ cmd: 'setSceneFlag', index: i, enabled });
        } catch (err) {
          logWarn('[backend setSceneFlag] failed', { index: i, enabled }, err);
          strictCatch(err, 'backend:setSceneFlag');
        }
      }
    }
    return resolveSnapshot(lastSnapshot);
  }

  function updateGeometryCaches(data = {}) {
    const makeView = (value, fallback, Ctor) => {
      if (ArrayBuffer.isView(value)) {
        return value;
      }
      if (Array.isArray(value) && Ctor) {
        try {
          return new Ctor(value);
        } catch (err) {
          strictCatch(err, 'backend:makeView');
          return fallback;
        }
      }
      return fallback;
    };
    const makeViewOrNull = (value, Ctor) => makeView(value, null, Ctor);
    lastSnapshot.xpos = makeView(data.xpos, new Float64Array(0), Float64Array);
    lastSnapshot.xmat = makeView(data.xmat, new Float64Array(0), Float64Array);
    if (typeof data.scn_ngeom === 'number' && Number.isFinite(data.scn_ngeom)) {
      lastSnapshot.scn_ngeom = data.scn_ngeom | 0;
    }
    applyViewFields(lastSnapshot, data, GEOM_VIEW_FIELDS_OPTIONAL, makeViewOrNull, { skipMissing: true });
    if (typeof data.nisland === 'number' && Number.isFinite(data.nisland)) lastSnapshot.nisland = data.nisland | 0;
    if (Array.isArray(data.eq_names)) lastSnapshot.eq_names = data.eq_names.slice();
    applyViewFields(lastSnapshot, data, GEOM_VIEW_FIELDS_ALWAYS, makeViewOrNull);
    lastSnapshot.contacts = data.contacts && typeof data.contacts === 'object' ? data.contacts : null;
  }

  const workerEventHandlers = {
    strict_report: (payload) => {
      const id = Number(payload.id) || 0;
      const pending = strictRequests.get(id);
      if (pending) {
        strictRequests.delete(id);
        pending.resolve(payload.report || null);
      }
    },
    run_state: (payload) => {
      if (typeof payload.running === 'boolean') {
        lastSnapshot.paused = !payload.running;
        lastSnapshot.pausedSource = payload.source || 'backend';
        notifyListeners();
      }
    },
    ready: (payload) => {
      perfMarkOnce('play:backend:worker_ready', {
        sentWallMs: (typeof payload?.perf?.sentWallMs === 'number') ? payload.perf.sentWallMs : null,
        transferMs: (typeof payload?.perf?.sentWallMs === 'number') ? (Date.now() - payload.perf.sentWallMs) : null,
        worker: payload?.perf && typeof payload.perf === 'object' ? payload.perf : null,
        ngeom: typeof payload.ngeom === 'number' ? (payload.ngeom | 0) : null,
      });
      lastFrameId = -1;
      lastSnapshot.history = createDefaultHistoryState();
      lastSnapshot.keyframes = createDefaultKeyframeState();
      lastSnapshot.watch = createDefaultWatchState();
      lastSnapshot.keyIndex = -1;
      if (typeof payload.ngeom === 'number') lastSnapshot.ngeom = payload.ngeom;
      if (typeof payload.nq === 'number') lastSnapshot.nq = payload.nq;
      if (typeof payload.nv === 'number') lastSnapshot.nv = payload.nv;
      if (payload.optionSupport) {
        lastSnapshot.optionSupport = payload.optionSupport;
      }
      if (payload.visual) {
        lastSnapshot.visual = cloneStruct(payload.visual);
        lastSnapshot.visualDefaults = cloneStruct(payload.visual);
        lastSnapshot.visualVersion = (lastSnapshot.visualVersion | 0) + 1;
        lastSnapshot.visualDefaultsVersion = (lastSnapshot.visualDefaultsVersion | 0) + 1;
      }
      if (payload.statistic) {
        lastSnapshot.statistic = cloneStruct(payload.statistic);
        lastSnapshot.statisticVersion = (lastSnapshot.statisticVersion | 0) + 1;
      }
      updateGeometryCaches(payload);
      if (payload.gesture) {
        lastSnapshot.gesture = {
          ...(lastSnapshot.gesture || {}),
          ...payload.gesture,
        };
      }
      if (payload.drag) {
        lastSnapshot.drag = {
          ...(lastSnapshot.drag || {}),
          ...payload.drag,
        };
      }
      if (payload.ctrl) {
        try {
          lastSnapshot.ctrl = Array.isArray(payload.ctrl)
            ? payload.ctrl.slice()
            : Array.from(payload.ctrl);
        } catch (err) {
          logWarn('[backend] ctrl decode failed', err);
          strictCatch(err, 'backend:ctrl_decode');
          lastSnapshot.ctrl = [];
        }
      }
      if (payload.options) {
        lastSnapshot.options = payload.options;
      }
      applyOptionSnapshot(payload);
      notifyListeners();
    },
    struct_state: (payload) => {
      if (payload.scope === 'mjVisual') {
        lastSnapshot.visual = payload.value || null;
        lastSnapshot.visualVersion = (lastSnapshot.visualVersion | 0) + 1;
      } else if (payload.scope === 'mjStatistic') {
        lastSnapshot.statistic = payload.value || null;
        lastSnapshot.statisticVersion = (lastSnapshot.statisticVersion | 0) + 1;
      }
      notifyListeners();
    },
    meta_cameras: (payload) => {
      lastSnapshot.cameras = Array.isArray(payload.cameras) ? payload.cameras : [];
      const totalModes = Math.max(1, 2 + (lastSnapshot.cameras?.length || 0));
      const mode = lastSnapshot.cameraMode | 0;
      if (mode >= totalModes) {
        lastSnapshot.cameraMode = 0;
        try { client.postMessage?.({ cmd: 'setCameraMode', mode: 0 }); } catch (err) { strictCatch(err, 'backend:setCameraMode'); }
      }
      notifyListeners();
    },
    meta_geoms: (payload) => {
      lastSnapshot.geoms = Array.isArray(payload.geoms) ? payload.geoms : [];
      notifyListeners();
    },
    selection: (payload) => {
      lastSnapshot.selection = {
        seq: Number(payload.seq) || 0,
        bodyId: Number(payload.bodyId) | 0,
        geomId: Number(payload.geomId) | 0,
        flexId: Number(payload.flexId) | 0,
        skinId: Number(payload.skinId) | 0,
        point: Array.isArray(payload.point)
          ? [Number(payload.point[0]) || 0, Number(payload.point[1]) || 0, Number(payload.point[2]) || 0]
          : [0, 0, 0],
        localpos: Array.isArray(payload.localpos)
          ? [Number(payload.localpos[0]) || 0, Number(payload.localpos[1]) || 0, Number(payload.localpos[2]) || 0]
          : [0, 0, 0],
        timestamp: Number(payload.timestamp) || 0,
      };
      notifyListeners();
    },
    meta_joints: (payload) => {
      const toI32 = (value) => {
        if (!value) return null;
        if (ArrayBuffer.isView(value)) {
          try { return new Int32Array(value); } catch (err) { strictCatch(err, 'backend:meta_joints_view'); return null; }
        }
        if (value instanceof ArrayBuffer) {
          try { return new Int32Array(value); } catch (err) { strictCatch(err, 'backend:meta_joints_buffer'); return null; }
        }
        if (Array.isArray(value)) {
          try { return Int32Array.from(value); } catch (err) { strictCatch(err, 'backend:meta_joints_array'); return null; }
        }
        return null;
      };
      const geomBody = toI32(payload.geom_bodyid);
      if (geomBody) lastSnapshot.geom_bodyid = geomBody;
      const bodyAdr = toI32(payload.body_jntadr);
      if (bodyAdr) lastSnapshot.body_jntadr = bodyAdr;
      const bodyNum = toI32(payload.body_jntnum);
      if (bodyNum) lastSnapshot.body_jntnum = bodyNum;
      const bodyParent = toI32(payload.body_parentid);
      if (bodyParent) lastSnapshot.body_parentid = bodyParent;
      const jtype = toI32(payload.jtype);
      if (jtype) lastSnapshot.jtype = jtype;
      if (typeof payload.nbody === 'number') lastSnapshot.nbody = payload.nbody | 0;
      if (typeof payload.njnt === 'number') lastSnapshot.njnt = payload.njnt | 0;
      const jqposadr = toI32(payload.jnt_qposadr);
      if (jqposadr) lastSnapshot.jnt_qposadr = jqposadr;
      const jrange = (() => {
        const source = payload.jnt_range;
        if (!source) return null;
        try {
          if (ArrayBuffer.isView(source)) return new Float64Array(source);
          if (Array.isArray(source)) return Float64Array.from(source);
          if (source instanceof ArrayBuffer) return new Float64Array(source);
        } catch (err) {
          strictCatch(err, 'backend:meta_joints_range');
        }
        return null;
      })();
      if (jrange) lastSnapshot.jnt_range = jrange;
      if (Array.isArray(payload.jnt_names)) {
        lastSnapshot.jnt_names = payload.jnt_names.map((name, idx) => String(name ?? `jnt ${idx}`));
      }
      notifyListeners();
    },
    meta: (payload) => {
      try {
        // Actuator metadata for dynamic control UI
        if (Array.isArray(payload.actuators)) {
          lastSnapshot.actuators = payload.actuators.map((a) => ({
            index: Number(a.index) | 0,
            name: String(a.name ?? `act ${a.index|0}`),
            min: Number(a.min),
            max: Number(a.max),
            step: Number.isFinite(+a.step) && +a.step > 0 ? +a.step : 0.001,
            value: Number(a.value) || 0,
          }));
          notifyListeners();
        }
      } catch (err) {
        strictCatch(err, 'backend:meta_actuators');
      }
    },
    snapshot: (payload) => {
      const tDecodeStart = perfEnabled ? perfNow() : 0;
      const recvWallMs = perfEnabled ? Date.now() : 0;
      if (perfEnabled) {
        perfMarkOnce('play:backend:first_snapshot', {
          sentWallMs: (typeof payload?.perf?.sentWallMs === 'number') ? payload.perf.sentWallMs : null,
          transferMs: (typeof payload?.perf?.sentWallMs === 'number') ? (recvWallMs - payload.perf.sentWallMs) : null,
          worker: payload?.perf && typeof payload.perf === 'object' ? payload.perf : null,
        });
      }
      const frameId = Number.isFinite(payload.frameId) ? (payload.frameId | 0) : null;
      if (frameId !== null) {
        if (frameId <= lastFrameId) {
          return;
        }
        lastFrameId = frameId;
        lastSnapshot.frameId = frameId;
      }
      if (typeof payload.tSim === 'number') lastSnapshot.t = payload.tSim;
      if (typeof payload.ngeom === 'number') lastSnapshot.ngeom = payload.ngeom;
      if (typeof payload.nq === 'number') lastSnapshot.nq = payload.nq;
      if (typeof payload.nv === 'number') lastSnapshot.nv = payload.nv;
      if (typeof payload.rate === 'number' && Number.isFinite(payload.rate)) {
        lastSnapshot.rate = payload.rate;
      }
      if (typeof payload.measuredSlowdown === 'number' && Number.isFinite(payload.measuredSlowdown)) {
        lastSnapshot.measuredSlowdown = payload.measuredSlowdown;
      }
      if (typeof payload.paused === 'boolean') {
        lastSnapshot.paused = payload.paused;
      }
      if (typeof payload.pausedSource === 'string') {
        lastSnapshot.pausedSource = payload.pausedSource;
      }
      if (typeof payload.rateSource === 'string') {
        lastSnapshot.rateSource = payload.rateSource;
      }
      if (payload.info && typeof payload.info === 'object') {
        lastSnapshot.info = { ...payload.info };
      }
      updateGeometryCaches(payload);
      if (payload.ctrl) {
        try {
          lastSnapshot.ctrl = Array.isArray(payload.ctrl)
            ? payload.ctrl.slice()
            : Array.from(payload.ctrl);
        } catch (err) {
          strictCatch(err, 'backend:ctrl_convert');
          lastSnapshot.ctrl = [];
        }
      }
      if (payload.optionSupport) {
        lastSnapshot.optionSupport = payload.optionSupport;
      }
      if (payload.history) {
        applyHistoryPayload(lastSnapshot, payload.history);
      }
      const keyIndexValue = Number.isFinite(payload.keyIndex) ? payload.keyIndex : null;
      if (payload.keyframes) {
        applyKeyframesPayload(lastSnapshot, payload.keyframes, keyIndexValue);
      } else if (keyIndexValue != null) {
        lastSnapshot.keyIndex = keyIndexValue | 0;
      }
      if (payload.watch) {
        applyWatchPayload(lastSnapshot, payload.watch, {
          clampSamples: false,
          computeSummary: false,
          requireFiniteIndex: false,
        });
      }
      if (payload.gesture) {
        lastSnapshot.gesture = {
          ...(lastSnapshot.gesture || {}),
          ...payload.gesture,
        };
      }
      if (payload.drag) {
        lastSnapshot.drag = {
          ...(lastSnapshot.drag || {}),
          ...payload.drag,
        };
      }
      if (payload.viewerCamera && typeof payload.viewerCamera === 'object') {
        lastSnapshot.viewerCamera = {
          type: Number.isFinite(payload.viewerCamera.type) ? (payload.viewerCamera.type | 0) : 0,
          lookat: Array.isArray(payload.viewerCamera.lookat)
            ? payload.viewerCamera.lookat.slice(0, 3).map((n) => Number(n) || 0)
            : [0, 0, 0],
          distance: Number(payload.viewerCamera.distance) || 0,
          azimuth: Number(payload.viewerCamera.azimuth) || 0,
          elevation: Number(payload.viewerCamera.elevation) || 0,
          orthographic: !!payload.viewerCamera.orthographic,
        };
      }
      if (payload.options) {
        lastSnapshot.options = payload.options;
      }
      applyOptionSnapshot(payload);
      if (perfEnabled) {
        const workerPerf = payload?.perf && typeof payload.perf === 'object' ? payload.perf : null;
        const ngeomValue = typeof payload.ngeom === 'number' ? (payload.ngeom | 0) : null;
        const scnNgeomValue = typeof payload.scn_ngeom === 'number' ? (payload.scn_ngeom | 0) : null;
        const decodeMs = perfNow() - tDecodeStart;
        perfSample('backend:snapshot_decode_ms', decodeMs, {
          frameId,
          ngeom: ngeomValue,
          scn_ngeom: scnNgeomValue,
        });
        if (workerPerf) {
          if (typeof workerPerf.snapshotMs === 'number' && Number.isFinite(workerPerf.snapshotMs)) {
            perfSample('worker:snapshot_ms', workerPerf.snapshotMs, {
              ngeom: ngeomValue,
              scn_ngeom: scnNgeomValue,
            });
          }
        }
        const sentWallMs = typeof payload?.perf?.sentWallMs === 'number' ? payload.perf.sentWallMs : null;
        if (sentWallMs != null) {
          perfSample('worker_to_main:snapshot_transfer_ms', recvWallMs - sentWallMs);
        }
        if ((payload?.scn_ngeom | 0) > 0) {
          perfMarkOnce('play:backend:first_scene_snapshot', {
            frameId,
            scn_ngeom: payload?.scn_ngeom | 0,
          });
        }
      }
      const tNotifyStart = perfEnabled ? perfNow() : 0;
      notifyListeners();
      if (perfEnabled) {
        perfSample('backend:notifyListeners_ms', perfNow() - tNotifyStart, {
          frameId,
          ngeom: typeof payload.ngeom === 'number' ? (payload.ngeom | 0) : null,
          scn_ngeom: typeof payload.scn_ngeom === 'number' ? (payload.scn_ngeom | 0) : null,
        });
      }
    },
    keyframes: (payload) => {
      applyKeyframesPayload(lastSnapshot, payload);
      notifyListeners();
    },
    history: (payload) => {
      applyHistoryPayload(lastSnapshot, payload);
      notifyListeners();
    },
    watch: (payload) => {
      applyWatchPayload(lastSnapshot, payload, {
        clampSamples: true,
        computeSummary: true,
        requireFiniteIndex: true,
      });
      notifyListeners();
    },
    render_assets: (payload) => {
      if (payload.assets) {
        lastSnapshot.renderAssets = payload.assets;
        notifyListeners();
        if (perfEnabled) {
          const recvWallMs = Date.now();
          const sentWallMs = typeof payload?.perf?.sentWallMs === 'number' ? payload.perf.sentWallMs : null;
          if (sentWallMs != null) {
            perfSample('worker_to_main:render_assets_transfer_ms', recvWallMs - sentWallMs);
          }
          if (typeof payload?.perf?.collectRenderAssetsMs === 'number' && Number.isFinite(payload.perf.collectRenderAssetsMs)) {
            perfSample('worker:collectRenderAssets_ms', payload.perf.collectRenderAssetsMs);
          }
          perfMarkOnce('play:backend:render_assets', {
            sentWallMs,
            transferMs: sentWallMs != null ? (recvWallMs - sentWallMs) : null,
            worker: payload?.perf && typeof payload.perf === 'object' ? payload.perf : null,
          });
        } else {
          perfMarkOnce('play:backend:render_assets');
        }
      }
    },
    gesture: (payload) => {
      if (payload.gesture) {
        lastSnapshot.gesture = {
          ...(lastSnapshot.gesture || {}),
          ...payload.gesture,
        };
      }
      if (payload.drag) {
        lastSnapshot.drag = {
          ...(lastSnapshot.drag || {}),
          ...payload.drag,
        };
      }
      applyOptionSnapshot(payload);
      notifyListeners();
    },
    align: (payload) => {
      const seq = Number(payload.seq) || ((lastSnapshot.align?.seq ?? 0) + 1);
      const center = Array.isArray(payload.center)
        ? payload.center.slice(0, 3).map((n) => Number(n) || 0)
        : lastSnapshot.align?.center ?? [0, 0, 0];
      const radius = Number(payload.radius) || lastSnapshot.align?.radius || 0;
      lastSnapshot.align = {
        seq,
        center,
        radius,
        source: payload.source || 'backend',
        timestamp: Number(payload.timestamp) || Date.now(),
      };
      notifyListeners();
    },
    copyState: (payload) => {
      const seq = Number(payload.seq) || ((lastSnapshot.copyState?.seq ?? 0) + 1);
      const precision = payload.precision || lastSnapshot.copyState?.precision || 'standard';
      const qposPreview = Array.isArray(payload.qposPreview)
        ? payload.qposPreview.map((n) => Number(n) || 0)
        : lastSnapshot.copyState?.qposPreview ?? [];
      const qvelPreview = Array.isArray(payload.qvelPreview)
        ? payload.qvelPreview.map((n) => Number(n) || 0)
        : lastSnapshot.copyState?.qvelPreview ?? [];
      const keyXml = buildCopyKeyXmlFromPayload(payload);
      lastSnapshot.copyState = {
        seq,
        precision,
        nq: Number(payload.nq) || 0,
        nv: Number(payload.nv) || 0,
        timestamp: Number(payload.timestamp) || Date.now(),
        complete: !!payload.complete,
        qposPreview,
        qvelPreview,
        keyXml: keyXml || null,
      };
      if (keyXml) {
        // Fire-and-forget clipboard write; errors are logged inside helper.
        void writeCopyKeyToClipboard(keyXml);
      }
      notifyListeners();
    },
    options: (payload) => {
      applyOptionSnapshot(payload);
      notifyListeners();
    },
    log: (payload) => {
      logStatus(`[backend] ${payload.message ?? ''}`, payload.extra ?? null);
    },
    error: (payload) => {
      const message =
        typeof payload.message === 'string' && payload.message.length
          ? payload.message
          : `Backend error: ${JSON.stringify(payload)}`;
      lastSnapshot.toast = { message, ts: Date.now() };
      lastSnapshot.backendError = message;
      logError('[backend error]', payload);
      notifyListeners();
    },
  };

  function handleMessage(event) {
    const data = event?.data ?? event;
    if (!data || typeof data !== 'object') return;
    try {
      dispatchEvent(workerEventHandlers, data);
    } catch (err) {
      strictCatch(err, `backend:worker_event:${String(data?.kind ?? 'unknown')}`);
    }
  }

  const initialXml = await loadDefaultXml();
  lastXmlText = typeof initialXml === 'string' ? initialXml : String(initialXml ?? '');
  await restartWorkerWithXml(initialXml);

  const uiHandlers = new Map([
    ['simulation.history_scrubber', (value) => {
      const offset = Math.min(0, normaliseInt(value, 0));
      try { client.postMessage?.({ cmd: 'historyScrub', offset }); } catch (err) {
        logWarn('[backend history] post failed', err);
        strictCatch(err, 'backend:history_scrub');
        throw err;
      }
      return true;
    }],
    ['simulation.key_slider', (value) => {
      const index = Math.max(-1, normaliseInt(value, -1));
      try {
        client.postMessage?.({ cmd: 'keyframeSelect', index });
      } catch (err) {
        logWarn('[backend keyframe select] failed', err);
        strictCatch(err, 'backend:keyframe_select');
        throw err;
      }
      return true;
    }],
    ['simulation.save_key', () => {
      const index = normaliseInt(lastSnapshot.keyIndex ?? -1, -1);
      try { client.postMessage?.({ cmd: 'keyframeSave', index }); } catch (err) {
        logWarn('[backend keyframe save] failed', err);
        strictCatch(err, 'backend:keyframe_save');
        throw err;
      }
      return true;
    }],
    ['simulation.load_key', () => {
      const index = Math.max(0, normaliseInt(lastSnapshot.keyIndex ?? 0, 0));
      try { client.postMessage?.({ cmd: 'keyframeLoad', index }); } catch (err) {
        logWarn('[backend keyframe load] failed', err);
        strictCatch(err, 'backend:keyframe_load');
        throw err;
      }
      return true;
    }],
    ['watch.field', (value) => {
      const field = typeof value === 'string' ? value.trim() : '';
      const nextField = field.length > 0 ? field : (lastSnapshot.watch?.field || '');
      if (!nextField) return true;
      try {
        client.postMessage?.({
          cmd: 'setWatch',
          field: nextField,
          index: Number.isFinite(lastSnapshot.watch?.index) ? (lastSnapshot.watch.index | 0) : 0,
        });
      } catch (err) {
        logWarn('[backend watch field] failed', err);
        strictCatch(err, 'backend:watch_field');
        throw err;
      }
      return true;
    }],
    ['watch.index', (value) => {
      const target = Math.max(0, normaliseInt(value, 0));
      try {
        client.postMessage?.({
          cmd: 'setWatch',
          field: lastSnapshot.watch?.field,
          index: target,
        });
      } catch (err) {
        logWarn('[backend watch index] failed', err);
        strictCatch(err, 'backend:watch_index');
        throw err;
      }
      return true;
    }],
    ['control.actuator', (value) => {
      try {
        const idx = Number(value?.index ?? value?.i ?? value?.id);
        const v = Number(value?.value ?? value?.v ?? 0);
        if (Number.isFinite(idx) && idx >= 0) {
          client.postMessage?.({ cmd: 'setCtrl', index: idx | 0, value: v });
        }
      } catch (err) {
        logWarn('[backend control.actuator] failed', err);
        strictCatch(err, 'backend:control_actuator');
        throw err;
      }
      return true;
    }],
    ['joint.slider', (value) => {
      try {
        const idx = Number(value?.index ?? value?.qposIndex ?? value?.i);
        const v = Number(value?.value ?? value?.v);
        if (Number.isFinite(idx) && idx >= 0 && Number.isFinite(v)) {
          const min = Number.isFinite(value?.min) ? Number(value.min) : null;
          const max = Number.isFinite(value?.max) ? Number(value.max) : null;
          client.postMessage?.({ cmd: 'setQpos', index: idx | 0, value: v, min, max });
        }
      } catch (err) {
        logWarn('[backend joint.slider] failed', err);
        strictCatch(err, 'backend:joint_slider');
        throw err;
      }
      return true;
    }],
    ['equality.toggle', (value) => {
      try {
        const idx = Number(value?.index ?? value?.i);
        const active = !!(value?.active ?? value?.value ?? value?.v);
        if (Number.isFinite(idx) && idx >= 0) {
          client.postMessage?.({ cmd: 'setEqualityActive', index: idx | 0, active });
        }
      } catch (err) {
        logWarn('[backend equality.toggle] failed', err);
        strictCatch(err, 'backend:equality_toggle');
        throw err;
      }
      return true;
    }],
    ['control.clear', () => {
      try {
        const acts = Array.isArray(lastSnapshot.actuators) ? lastSnapshot.actuators : [];
        for (let i = 0; i < acts.length; i += 1) {
          client.postMessage?.({ cmd: 'setCtrl', index: i, value: 0 });
        }
      } catch (err) {
        logWarn('[backend control.clear] failed', err);
        strictCatch(err, 'backend:control_clear');
        throw err;
      }
      return true;
    }],
  ]);

  const bindingExactHandlers = new Map([
    ['Simulate::camera', (value) => {
      const totalModes = Math.max(1, 2 + (lastSnapshot.cameras?.length || 0));
      const modeValue = Math.max(0, Math.min(totalModes - 1, Math.trunc(toNumber(value))));
      try {
        client.postMessage?.({ cmd: 'setCameraMode', mode: modeValue });
      } catch (err) {
        logWarn('[backend camera] post failed', err);
        strictCatch(err, 'backend:camera');
        throw err;
      }
      return true;
    }],
    ['Simulate::tracking_geom', () => true],
    ['mjvOption::label', (value) => {
      const mode = Math.max(0, Math.trunc(toNumber(value)));
      try {
        client.postMessage?.({ cmd: 'setLabelMode', mode });
      } catch (err) {
        logWarn('[backend label mode] post failed', err);
        strictCatch(err, 'backend:label_mode');
        throw err;
      }
      return true;
    }],
    ['mjvOption::frame', (value) => {
      const mode = Math.max(0, Math.trunc(toNumber(value)));
      try {
        client.postMessage?.({ cmd: 'setFrameMode', mode });
      } catch (err) {
        logWarn('[backend frame mode] post failed', err);
        strictCatch(err, 'backend:frame_mode');
        throw err;
      }
      return true;
    }],
  ]);

  const bindingRegexHandlers = [
    {
      pattern: /^Simulate::opt\.(flex_layer|bvh_depth)$/,
      handle: (match, value) => {
        const field = match[1];
        const nextValue = Math.max(0, Math.trunc(toNumber(value)));
        try {
          client.postMessage?.({
            cmd: 'setVisualOption',
            field,
            value: nextValue,
          });
        } catch (err) {
          logWarn('[backend setVisualOption] post failed', err);
          strictCatch(err, 'backend:set_visual_option');
          throw err;
        }
        return true;
      },
    },
    {
      pattern: /^mjvOption::(geom|site|joint|tendon|actuator|flex|skin)group\[(\d+)\]$/,
      handle: (match, value) => {
        const type = match[1];
        const idx = Math.max(0, Math.trunc(toNumber(match[2])));
        if (idx < MJ_GROUP_COUNT) {
          try {
            client.postMessage?.({ cmd: 'setGroupState', group: type, index: idx, enabled: bool(value) });
          } catch (err) {
            logWarn('[backend group] post failed', err);
            strictCatch(err, 'backend:group');
            throw err;
          }
        }
        return true;
      },
    },
    {
      pattern: /^mjvOption::flags\[(\d+)\]$/,
      handle: (match, value) => {
        const idx = Number(match[1]);
        const enabled = bool(value);
        try {
          client.postMessage?.({ cmd: 'setVoptFlag', index: idx, enabled });
        } catch (err) {
          logWarn('[backend vopt flag] post failed', err);
          strictCatch(err, 'backend:vopt_flag');
          throw err;
        }
        return true;
      },
    },
    {
      pattern: /^mjvScene::flags\[(\d+)\]$/,
      handle: (match, value) => {
        const idx = Number(match[1]);
        const enabled = bool(value);
        try {
          client.postMessage?.({ cmd: 'setSceneFlag', index: idx, enabled });
        } catch (err) {
          logWarn('[backend scene flag] post failed', err);
          strictCatch(err, 'backend:scene_flag');
          throw err;
        }
        return true;
      },
    },
  ];

  function dispatchBinding(binding, value) {
    if (!binding) return false;
    const exactHandler = bindingExactHandlers.get(binding);
    if (exactHandler) {
      exactHandler(value);
      return true;
    }
    if (applySimulateMaskBinding(binding, value, 'Simulate::disable', 'disableflags', false, 'disableflags')) {
      return true;
    }
    if (applySimulateMaskBinding(binding, value, 'Simulate::enable', 'enableflags', false, 'enableflags')) {
      return true;
    }
    if (applySimulateMaskBinding(binding, value, 'Simulate::enableactuator', 'disableactuator', true, 'disableactuator')) {
      return true;
    }
    for (const entry of bindingRegexHandlers) {
      const match = binding.match(entry.pattern);
      if (!match) continue;
      entry.handle(match, value);
      return true;
    }
    return false;
  }

  async function apply(payload) {
    if (!payload) {
      return resolveSnapshot(lastSnapshot);
    }
    if (payload.kind === 'gesture') {
      const mode = payload.mode ?? payload.gesture?.mode ?? 'idle';
      const phase = payload.phase ?? payload.gesture?.phase ?? 'update';
      const gestureType = typeof payload.gestureType === 'string' ? payload.gestureType : null;
      const pointerSource = payload.pointer ?? payload.gesture?.pointer ?? null;
      const pointer = pointerSource
        ? {
            x: Number(pointerSource.x) || 0,
            y: Number(pointerSource.y) || 0,
            dx: Number(pointerSource.dx) || 0,
            dy: Number(pointerSource.dy) || 0,
            buttons: Number(pointerSource.buttons ?? 0),
            pressure: Number(pointerSource.pressure ?? 0),
          }
        : null;
      const dragSource = payload.drag ?? (pointer ? { dx: pointer.dx, dy: pointer.dy } : null);
      const gesture = {
        mode: phase === 'end' ? 'idle' : mode,
        phase,
        pointer,
      };
      const drag = dragSource
        ? {
            dx: Number(dragSource.dx) || 0,
            dy: Number(dragSource.dy) || 0,
          }
        : (phase === 'end' ? { dx: 0, dy: 0 } : null);
      try {
        client.postMessage?.({
          cmd: 'gesture',
          gesture,
          pointer,
          drag,
          gestureType,
          reldx: Number(payload.reldx),
          reldy: Number(payload.reldy),
          shiftKey: !!payload.shiftKey,
          cam: payload.cam || null,
        });
      } catch (err) {
        logError('[backend gesture] failed', err);
        strictCatch(err, 'backend:gesture');
      }
      return resolveSnapshot(lastSnapshot);
    }
    if (payload.kind !== 'ui') {
      return resolveSnapshot(lastSnapshot);
    }
    const { id, value, control } = payload;
    const binding = typeof control?.binding === 'string' ? control.binding : null;
    if (dispatchBinding(binding, value)) {
      return resolveSnapshot(lastSnapshot);
    }
    const uiHandler = uiHandlers.get(id);
    if (uiHandler) {
      uiHandler(value);
      return resolveSnapshot(lastSnapshot);
    }
    const prepared = typeof options.prepareBindingUpdate === 'function'
      ? await options.prepareBindingUpdate(control, value)
      : null;
    if (prepared) {
      try {
        client.postMessage?.({
          cmd: 'setField',
          target: prepared.meta.scope,
          path: prepared.meta.path,
          kind: prepared.meta.kind,
          size: prepared.meta.size,
          value: prepared.value,
        });
        // Force a fresh snapshot so UI can observe the updated struct fields,
        // even when the worker is paused or snapshot delivery is delayed.
        client.postMessage?.({ cmd: 'snapshot' });
      } catch (err) {
        logWarn('[backend setField] post failed', err);
        strictCatch(err, 'backend:setField_post');
      }
      return resolveSnapshot(lastSnapshot);
    }
    switch (id) {
      case 'simulation.run': {
        const run = value === 'Run' || value === true || value === 1;
        return setRunState(run, 'ui');
      }
      case 'simulation.reset':
        client.postMessage?.({ cmd: 'reset' });
        break;
      case 'simulation.reload': {
        if (lastXmlText && typeof lastXmlText === 'string' && lastXmlText.trim().length > 0) {
          return restartWorkerWithXml(lastXmlText);
        }
        const xmlText = await loadDefaultXml();
        lastXmlText = typeof xmlText === 'string' ? xmlText : String(xmlText ?? '');
        return restartWorkerWithXml(xmlText);
      }
      case 'simulation.align': {
        try {
          client.postMessage?.({ cmd: 'align', source: 'ui' });
        } catch (err) {
          logWarn('[backend align] post failed', err);
          strictCatch(err, 'backend:align');
        }
        break;
      }
      case 'simulation.copy_state': {
        const meta = value && typeof value === 'object' ? value : {};
        const precision = meta.shiftKey ? 'full' : 'standard';
        try {
          client.postMessage?.({ cmd: 'copyState', precision, source: 'ui' });
        } catch (err) {
          logWarn('[backend copyState] post failed', err);
          strictCatch(err, 'backend:copy_state');
        }
        break;
      }
      case 'simulation.noise_scale':
      case 'simulation.noise_rate':
        // Noise controls are disabled in this build; UI state is still
        // tracked via Simulate::ctrl_noise_* bindings but no messages are
        // sent to the worker.
        break;
      case 'rendering.camera_mode':
      case 'option.help':
      default:
        break;
    }
    return resolveSnapshot(lastSnapshot);
  }

  function snapshot() {
    return resolveSnapshot(lastSnapshot);
  }

  function subscribe(fn) {
    listeners.add(fn);
    fn(resolveSnapshot(lastSnapshot));
    return () => listeners.delete(fn);
  }

  async function step(direction = 1) {
    const dir = direction >= 0 ? 1 : -1;
    const history = lastSnapshot.history || createDefaultHistoryState();
    const currentOffset = Number.isFinite(history.scrubIndex) ? history.scrubIndex : 0;
    const count = Number.isFinite(history.count) ? history.count : 0;
    let nextOffset = currentOffset;

    if (currentOffset !== 0 || (dir < 0 && count > 0)) {
      if (currentOffset === 0) {
        if (dir < 0) {
          nextOffset = -1;
        }
      } else if (dir > 0) {
        nextOffset = Math.min(0, currentOffset + 1);
      } else if (dir < 0) {
        const minOffset = -Math.max(0, count);
        nextOffset = Math.max(minOffset, currentOffset - 1);
      }

      if (nextOffset === currentOffset) {
        return resolveSnapshot(lastSnapshot);
      }

      try {
        client.postMessage?.({ cmd: 'historyScrub', offset: nextOffset });
      } catch (err) {
        logWarn('[backend history step] post failed', err);
        strictCatch(err, 'backend:history_step');
      }
      return resolveSnapshot(lastSnapshot);
    }

    setRunState(false, 'ui');
    const n = Math.max(1, Math.abs(direction | 0) || 1);
    try {
      client.postMessage?.({ cmd: 'step', n });
    } catch (err) {
      logWarn('[backend step] post failed', err);
      strictCatch(err, 'backend:step');
    }
    return resolveSnapshot(lastSnapshot);
  }

  async function setCameraIndex() {
    return resolveSnapshot(lastSnapshot);
  }

  const toVec3 = (value) => {
    if (Array.isArray(value)) {
      return [
        Number(value[0]) || 0,
        Number(value[1]) || 0,
        Number(value[2]) || 0,
      ];
    }
    return [0, 0, 0];
  };

  async function applyPerturbCommand(options = {}) {
    const phase = typeof options.phase === 'string' ? options.phase : '';
    if (!phase) return resolveSnapshot(lastSnapshot);

    const msg = { cmd: 'applyPerturb', phase };
    const mode = options.mode === 'rotate' ? 'rotate' : 'translate';
    const cam = options.cam && typeof options.cam === 'object' ? options.cam : null;
    const camPayload = cam
      ? {
          lookat: toVec3(cam.lookat),
          distance: Number(cam.distance) || 0,
          azimuth: Number(cam.azimuth) || 0,
          elevation: Number(cam.elevation) || 0,
          orthographic: !!cam.orthographic,
        }
      : null;

    if (phase === 'begin') {
      msg.mode = mode;
      msg.shiftKey = !!options.shiftKey;
      const bodyIdRaw = Number(options.bodyId);
      if (Number.isFinite(bodyIdRaw) && (bodyIdRaw | 0) > 0) {
        msg.bodyId = bodyIdRaw | 0;
        if (Array.isArray(options.localpos)) {
          msg.localpos = toVec3(options.localpos);
        }
      }
      const scaleRaw = Number(options.scale);
      if (Number.isFinite(scaleRaw) && scaleRaw > 0) {
        msg.scale = scaleRaw;
      }
      if (camPayload) msg.cam = camPayload;
    } else if (phase === 'move') {
      msg.mode = mode;
      msg.shiftKey = !!options.shiftKey;
      msg.reldx = Number(options.reldx) || 0;
      msg.reldy = Number(options.reldy) || 0;
      if (camPayload) msg.cam = camPayload;
    } else if (phase === 'end') {
      // nothing else
    } else {
      return resolveSnapshot(lastSnapshot);
    }

    try {
      client.postMessage?.(msg);
    } catch (err) {
      logWarn('[backend applyPerturb] failed', err);
      strictCatch(err, 'backend:applyPerturb');
    }
    return resolveSnapshot(lastSnapshot);
  }

  async function setSelectionCommand(options = {}) {
    const bodyId = Number(options.bodyId) | 0;
    const msg = { cmd: 'setSelection', bodyId };
    if (Array.isArray(options.localpos)) {
      msg.localpos = toVec3(options.localpos);
    }
    try {
      client.postMessage?.(msg);
    } catch (err) {
      logWarn('[backend setSelection] failed', err);
      strictCatch(err, 'backend:setSelection');
    }
    return resolveSnapshot(lastSnapshot);
  }

  async function selectAtCommand(options = {}) {
    const relxRaw = Number(options.relx);
    const relyRaw = Number(options.rely);
    const aspectRaw = Number(options.aspect);
    const msg = {
      cmd: 'selectAt',
      relx: Number.isFinite(relxRaw) ? relxRaw : 0,
      rely: Number.isFinite(relyRaw) ? relyRaw : 0,
      aspect: Number.isFinite(aspectRaw) && aspectRaw > 0 ? aspectRaw : 1,
    };
    try {
      client.postMessage?.(msg);
    } catch (err) {
      logWarn('[backend selectAt] failed', err);
      strictCatch(err, 'backend:selectAt');
    }
    return resolveSnapshot(lastSnapshot);
  }

  function dispose() {
    if (messageHandler) {
      try { client.removeEventListener?.('message', messageHandler); } catch (err) { strictCatch(err, 'backend:dispose_listener'); }
    }
    client?.terminate?.();
  }

  return {
    kind,
    apply,
    snapshot,
    subscribe,
    step,
    setCameraIndex,
    setRunState,
    setRate,
    applyPerturb: applyPerturbCommand,
    setSelection: setSelectionCommand,
    selectAt: selectAtCommand,
    setVisualState: applyVisualStatePayload,
    loadXmlText,
    getStrictReport: async () => ({
      main: getStrictReport(),
      worker: await requestWorkerStrictReport(),
    }),
    getInitialModelInfo: () => initialModelInfo,
    dispose,
  };
}
