// Auto-generated by tools/generate_ui_artifacts.mjs. Do not edit by hand.

const VOPT_FLAG_DEFAULT_INDICES = Object.freeze([1,7,8,13,22,23,25,27]);

function makeFlagArray(length, enabledIndices) {
  const flags = Array.from({ length }, () => false);
  for (const idx of enabledIndices) {
    if (idx >= 0 && idx < flags.length) {
      flags[idx] = true;
    }
  }
  return flags;
}

export const MJ_GROUP_TYPES = Object.freeze(["geom","site","joint","tendon","actuator","flex","skin"]);
export const MJ_GROUP_COUNT = 6;

export const SCENE_FLAG_DEFAULTS = Object.freeze([true,false,true,false,true,false,true,false,false,true]);

export const DEFAULT_VOPT_FLAGS = Object.freeze(makeFlagArray(32, VOPT_FLAG_DEFAULT_INDICES));

export const SCENE_FLAG_DEFAULTS_NUMERIC = Object.freeze(
  SCENE_FLAG_DEFAULTS.map((flag) => (flag ? 1 : 0)),
);
export const DEFAULT_VOPT_FLAGS_NUMERIC = Object.freeze(
  DEFAULT_VOPT_FLAGS.map((flag) => (flag ? 1 : 0)),
);

export const REALTIME_LEVELS = Object.freeze([800,400,200,150,120,100,80,66,50,40,33,25,20,16,13,10,8,6.6,5,4,3.3,2.5,2,1.6,1.3,1,0.8,0.66,0.5,0.4,0.33,0.25,0.2,0.16,0.13,0.1]);

export const DEFAULT_REALTIME_INDEX = Math.max(0, REALTIME_LEVELS.indexOf(100));

