
// AUTO-GENERATED. Do not edit by hand. Source: codegen/spec_337.yaml
// This file reflects the C/WASM ABI: views (pointer getters) and dims (int getters)
// Values are accessed via Module.HEAP* typed arrays using the returned pointer.

export interface MjModule {
  ccall(name: string, returnType: string | null, argTypes?: string[], args?: any[]): any;
  HEAPF64: Float64Array;
  HEAP32: Int32Array;
  HEAPU8: Uint8Array;
}

// Lifecycle / compute / time
export function mjwf_make_from_xml(path: string): number;
export function mjwf_free(h: number): void;
export function mjwf_valid(h: number): number;
export function mjwf_step(h: number, n: number): number;
export function mjwf_forward(h: number): number;
export function mjwf_reset(h: number): number;
export function mjwf_timestep(h: number): number;
export function mjwf_time(h: number): number;

// Mass matrix (dense nv*nv)
export function mjwf_calc_M(h: number): number;
export function mjwf_M_ptr(h: number): number;
export function mjwf_M_size(h: number): number;

// Sensor meta
export function mjwf_sensor_dim(h: number, sensorId: number): number;
export function mjwf_sensor_adr(h: number, sensorId: number): number;
export function mjwf_sensor_type(h: number, sensorId: number): number;

// Names helpers (pointers or pointer->string via UTF8)
export function mjwf_name_at(h: number, type: number, id: number): number;
export function mjwf_name2id(h: number, type: number, name: string): number;

// Contacts (opaque struct pointer and sizeof)
export function mjwf_contact_ptr(h: number): number;
export function mjwf_contact_sizeof(): number;

// ABI / versioning
export function mjwf_abi_version(): number;
export function mjwf_layout_hash(): number;
export function mjwf_version_string(): number;

// --- Auto-generated from spec: dims ---

export function mjwf_nq(h: number): number;
export function mjwf_nv(h: number): number;
export function mjwf_nu(h: number): number;
export function mjwf_njnt(h: number): number;
export function mjwf_nbody(h: number): number;
export function mjwf_ngeom(h: number): number;
export function mjwf_nsite(h: number): number;
export function mjwf_ncam(h: number): number;
export function mjwf_nlight(h: number): number;
export function mjwf_nmocap(h: number): number;
export function mjwf_ntendon(h: number): number;
export function mjwf_nsensordata(h: number): number;
export function mjwf_nnames(h: number): number;
export function mjwf_nM(h: number): number;
export function mjwf_nC(h: number): number;
export function mjwf_nhfield(h: number): number;
export function mjwf_nhfielddata(h: number): number;
export function mjwf_ntex(h: number): number;
export function mjwf_nmat(h: number): number;
export function mjwf_nmesh(h: number): number;
export function mjwf_nmeshvert(h: number): number;
export function mjwf_nmeshface(h: number): number;
export function mjwf_nmeshtexcoord(h: number): number;
export function mjwf_nmeshgraph(h: number): number;
export function mjwf_ntexdata(h: number): number;
export function mjwf_nefc(h: number): number;
export function mjwf_ncon(h: number): number;
export function mjwf_nJ(h: number): number;
export function mjwf_nA(h: number): number;
export function mjwf_nisland(h: number): number;
export function mjwf_nskin(h: number): number;
export function mjwf_nskinvert(h: number): number;
export function mjwf_nskintexvert(h: number): number;
export function mjwf_nskinface(h: number): number;
export function mjwf_nskinbone(h: number): number;
export function mjwf_nskinbonevert(h: number): number;

// --- Auto-generated from spec: pointer getters (views) ---
export function mjwf_qpos_ptr(h: number): number;
export function mjwf_qvel_ptr(h: number): number;
export function mjwf_ctrl_ptr(h: number): number;
export function mjwf_sensordata_ptr(h: number): number;
export function mjwf_qacc_ptr(h: number): number;
export function mjwf_qfrc_inverse_ptr(h: number): number;
export function mjwf_qfrc_actuator_ptr(h: number): number;
export function mjwf_qfrc_bias_ptr(h: number): number;
export function mjwf_qfrc_passive_ptr(h: number): number;
export function mjwf_cfrc_ext_ptr(h: number): number;
export function mjwf_ten_length_ptr(h: number): number;
export function mjwf_actuator_length_ptr(h: number): number;
export function mjwf_xipos_ptr(h: number): number;
export function mjwf_ximat_ptr(h: number): number;
export function mjwf_xquat_ptr(h: number): number;
export function mjwf_cvel_ptr(h: number): number;
export function mjwf_cacc_ptr(h: number): number;
export function mjwf_cdof_ptr(h: number): number;
export function mjwf_cdof_dot_ptr(h: number): number;
export function mjwf_cinert_ptr(h: number): number;
export function mjwf_crb_ptr(h: number): number;
export function mjwf_efc_type_ptr(h: number): number;
export function mjwf_efc_id_ptr(h: number): number;
export function mjwf_efc_state_ptr(h: number): number;
export function mjwf_efc_force_ptr(h: number): number;
export function mjwf_efc_pos_ptr(h: number): number;
export function mjwf_efc_J_ptr(h: number): number;
export function mjwf_efc_J_colind_ptr(h: number): number;
export function mjwf_efc_J_rownnz_ptr(h: number): number;
export function mjwf_efc_J_rowadr_ptr(h: number): number;
export function mjwf_efc_J_rowsuper_ptr(h: number): number;
export function mjwf_efc_AR_ptr(h: number): number;
export function mjwf_efc_AR_colind_ptr(h: number): number;
export function mjwf_efc_margin_ptr(h: number): number;
export function mjwf_efc_frictionloss_ptr(h: number): number;
export function mjwf_efc_diagApprox_ptr(h: number): number;
export function mjwf_efc_KBIP_ptr(h: number): number;
export function mjwf_efc_D_ptr(h: number): number;
export function mjwf_efc_R_ptr(h: number): number;
export function mjwf_efc_vel_ptr(h: number): number;
export function mjwf_efc_aref_ptr(h: number): number;
export function mjwf_efc_b_ptr(h: number): number;
export function mjwf_efc_island_ptr(h: number): number;
export function mjwf_map_efc2iefc_ptr(h: number): number;
export function mjwf_map_iefc2efc_ptr(h: number): number;
export function mjwf_island_nv_ptr(h: number): number;
export function mjwf_island_idofadr_ptr(h: number): number;
export function mjwf_island_dofadr_ptr(h: number): number;
export function mjwf_island_ne_ptr(h: number): number;
export function mjwf_island_nf_ptr(h: number): number;
export function mjwf_island_nefc_ptr(h: number): number;
export function mjwf_island_iefcadr_ptr(h: number): number;
export function mjwf_iefc_type_ptr(h: number): number;
export function mjwf_iefc_id_ptr(h: number): number;
export function mjwf_iefc_J_ptr(h: number): number;
export function mjwf_iefc_J_colind_ptr(h: number): number;
export function mjwf_iefc_frictionloss_ptr(h: number): number;
export function mjwf_iefc_D_ptr(h: number): number;
export function mjwf_iefc_R_ptr(h: number): number;
export function mjwf_iefc_aref_ptr(h: number): number;
export function mjwf_iefc_state_ptr(h: number): number;
export function mjwf_iefc_force_ptr(h: number): number;
export function mjwf_names_ptr(h: number): number;
export function mjwf_name_bodyadr_ptr(h: number): number;
export function mjwf_name_jntadr_ptr(h: number): number;
export function mjwf_name_geomadr_ptr(h: number): number;
export function mjwf_name_siteadr_ptr(h: number): number;
export function mjwf_name_camadr_ptr(h: number): number;
export function mjwf_name_lightadr_ptr(h: number): number;
export function mjwf_name_tendonadr_ptr(h: number): number;
export function mjwf_name_actuatoradr_ptr(h: number): number;
export function mjwf_name_sensoradr_ptr(h: number): number;
export function mjwf_body_parentid_ptr(h: number): number;
export function mjwf_body_pos_ptr(h: number): number;
export function mjwf_body_quat_ptr(h: number): number;
export function mjwf_jnt_type_ptr(h: number): number;
export function mjwf_jnt_qposadr_ptr(h: number): number;
export function mjwf_jnt_dofadr_ptr(h: number): number;
export function mjwf_dof_bodyid_ptr(h: number): number;
export function mjwf_dof_parentid_ptr(h: number): number;
export function mjwf_geom_type_ptr(h: number): number;
export function mjwf_geom_size_ptr(h: number): number;
export function mjwf_geom_rbound_ptr(h: number): number;
export function mjwf_geom_friction_ptr(h: number): number;
export function mjwf_geom_solref_ptr(h: number): number;
export function mjwf_geom_solimp_ptr(h: number): number;
export function mjwf_body_ipos_ptr(h: number): number;
export function mjwf_body_iquat_ptr(h: number): number;
export function mjwf_body_mass_ptr(h: number): number;
export function mjwf_body_inertia_ptr(h: number): number;
export function mjwf_jnt_axis_ptr(h: number): number;
export function mjwf_jnt_range_ptr(h: number): number;
export function mjwf_actuator_trnid_ptr(h: number): number;
export function mjwf_actuator_ctrllimited_ptr(h: number): number;
export function mjwf_actuator_ctrlrange_ptr(h: number): number;
export function mjwf_tendon_limited_ptr(h: number): number;
export function mjwf_tendon_range_ptr(h: number): number;
export function mjwf_sensor_type_m_ptr(h: number): number;
export function mjwf_sensor_objid_ptr(h: number): number;
export function mjwf_sensor_dim_m_ptr(h: number): number;
export function mjwf_sensor_adr_m_ptr(h: number): number;
export function mjwf_hfield_size_ptr(h: number): number;
export function mjwf_hfield_nrow_ptr(h: number): number;
export function mjwf_hfield_ncol_ptr(h: number): number;
export function mjwf_hfield_adr_ptr(h: number): number;
export function mjwf_hfield_data_ptr(h: number): number;
export function mjwf_tex_type_ptr(h: number): number;
export function mjwf_tex_colorspace_ptr(h: number): number;
export function mjwf_tex_height_ptr(h: number): number;
export function mjwf_tex_width_ptr(h: number): number;
export function mjwf_tex_nchannel_ptr(h: number): number;
export function mjwf_tex_adr_ptr(h: number): number;
export function mjwf_tex_data_ptr(h: number): number;
export function mjwf_mat_texid_ptr(h: number): number;
export function mjwf_mat_texuniform_ptr(h: number): number;
export function mjwf_mat_texrepeat_ptr(h: number): number;
export function mjwf_mat_emission_ptr(h: number): number;
export function mjwf_mat_specular_ptr(h: number): number;
export function mjwf_mat_shininess_ptr(h: number): number;
export function mjwf_mat_reflectance_ptr(h: number): number;
export function mjwf_mat_metallic_ptr(h: number): number;
export function mjwf_mat_roughness_ptr(h: number): number;
export function mjwf_mat_rgba_ptr(h: number): number;
export function mjwf_mesh_vertadr_ptr(h: number): number;
export function mjwf_mesh_vertnum_ptr(h: number): number;
export function mjwf_mesh_faceadr_ptr(h: number): number;
export function mjwf_mesh_facenum_ptr(h: number): number;
export function mjwf_mesh_vert_ptr(h: number): number;
export function mjwf_mesh_face_ptr(h: number): number;
export function mjwf_mesh_texcoord_ptr(h: number): number;
export function mjwf_mesh_facenormal_ptr(h: number): number;
export function mjwf_mesh_facetexcoord_ptr(h: number): number;
export function mjwf_mesh_graph_ptr(h: number): number;
export function mjwf_qM_ptr(h: number): number;
export function mjwf_M_csr_ptr(h: number): number;
export function mjwf_body_xpos_ptr(h: number): number;
export function mjwf_body_xmat_ptr(h: number): number;
export function mjwf_geom_xpos_ptr(h: number): number;
export function mjwf_geom_xmat_ptr(h: number): number;
export function mjwf_site_xpos_ptr(h: number): number;
export function mjwf_site_xmat_ptr(h: number): number;
export function mjwf_cam_xpos_ptr(h: number): number;
export function mjwf_cam_xmat_ptr(h: number): number;
export function mjwf_light_xpos_ptr(h: number): number;
export function mjwf_light_xdir_ptr(h: number): number;
export function mjwf_mocap_pos_ptr(h: number): number;
export function mjwf_mocap_quat_ptr(h: number): number;
export function mjwf_flex_contype_ptr(h: number): number;
export function mjwf_flex_conaffinity_ptr(h: number): number;
export function mjwf_flex_condim_ptr(h: number): number;
export function mjwf_flex_priority_ptr(h: number): number;
export function mjwf_flex_solmix_ptr(h: number): number;
export function mjwf_flex_solref_ptr(h: number): number;
export function mjwf_flex_solimp_ptr(h: number): number;
export function mjwf_flex_friction_ptr(h: number): number;
export function mjwf_flex_margin_ptr(h: number): number;
export function mjwf_flex_gap_ptr(h: number): number;
export function mjwf_flex_internal_ptr(h: number): number;
export function mjwf_flex_selfcollide_ptr(h: number): number;
export function mjwf_flex_passive_ptr(h: number): number;
export function mjwf_flex_dim_ptr(h: number): number;
export function mjwf_flex_matid_ptr(h: number): number;
export function mjwf_flex_group_ptr(h: number): number;
export function mjwf_flex_vert_ptr(h: number): number;
export function mjwf_flex_vert0_ptr(h: number): number;
export function mjwf_flex_node_ptr(h: number): number;
export function mjwf_flex_node0_ptr(h: number): number;
export function mjwf_flex_nodebodyid_ptr(h: number): number;
export function mjwf_flex_vertbodyid_ptr(h: number): number;
export function mjwf_flex_edge_ptr(h: number): number;
export function mjwf_flex_edgeflap_ptr(h: number): number;
export function mjwf_flex_elem_ptr(h: number): number;
export function mjwf_flex_elemedge_ptr(h: number): number;
export function mjwf_flex_elemlayer_ptr(h: number): number;
export function mjwf_flex_shell_ptr(h: number): number;
export function mjwf_flex_evpair_ptr(h: number): number;
export function mjwf_flex_radius_ptr(h: number): number;
export function mjwf_flex_stiffness_ptr(h: number): number;
export function mjwf_flex_bending_ptr(h: number): number;
export function mjwf_flex_damping_ptr(h: number): number;
export function mjwf_flex_flatskin_ptr(h: number): number;
export function mjwf_flex_rgba_ptr(h: number): number;
export function mjwf_flex_texcoord_ptr(h: number): number;
export function mjwf_skin_vert_ptr(h: number): number;
export function mjwf_skin_texcoord_ptr(h: number): number;
export function mjwf_skin_face_ptr(h: number): number;
export function mjwf_skin_matid_ptr(h: number): number;
export function mjwf_skin_group_ptr(h: number): number;
export function mjwf_skin_rgba_ptr(h: number): number;
export function mjwf_skin_inflate_ptr(h: number): number;
export function mjwf_skin_vertadr_ptr(h: number): number;
export function mjwf_skin_vertnum_ptr(h: number): number;
export function mjwf_skin_texcoordadr_ptr(h: number): number;
export function mjwf_skin_faceadr_ptr(h: number): number;
export function mjwf_skin_facenum_ptr(h: number): number;
export function mjwf_skin_boneadr_ptr(h: number): number;
export function mjwf_skin_bonenum_ptr(h: number): number;
export function mjwf_skin_bonevertadr_ptr(h: number): number;
export function mjwf_skin_bonevertnum_ptr(h: number): number;
export function mjwf_skin_bonebindpos_ptr(h: number): number;
export function mjwf_skin_bonebindquat_ptr(h: number): number;
export function mjwf_skin_bonebodyid_ptr(h: number): number;
export function mjwf_skin_bonevertid_ptr(h: number): number;
export function mjwf_skin_bonevertweight_ptr(h: number): number;
export function mjwf_skin_pathadr_ptr(h: number): number;
