// Auto-generated by tools/generate_ui_artifacts.mjs. Do not edit by hand.
//
// Type definitions for the runtime state helpers located in `ui/state.mjs`
// and `ui/viewer_actions.mjs`. This file exists for editor tooling only; the
// browser runtime continues to use plain JS modules.

export interface OverlayState {
  help: boolean;
  info: boolean;
  profiler: boolean;
  sensor: boolean;
  fullscreen: boolean;
  vsync: boolean;
  busywait: boolean;
  pauseUpdate: boolean;
}

export interface DragState {
  dx: number;
  dy: number;
}

export interface GesturePointer {
  x: number;
  y: number;
  dx: number;
  dy: number;
  buttons: number;
  pressure: number;
}

export interface GestureState {
  mode: string;
  phase: string;
  pointer?: GesturePointer | null;
}

export interface PerturbState {
  mode: string;
  active: boolean;
}

export interface RuntimeState {
  cameraIndex: number;
  trackingGeom: number;
  lastAction: string;
  gesture: GestureState;
  drag: DragState;
  perturb: PerturbState;
}

export interface ThemeState {
  color: number;
  spacing: number;
  font: number;
}

export interface PanelState {
  left: boolean;
  right: boolean;
}

export interface ShellState {
  modelLabel: string;
}

export interface RenderingOptionsState {
  materials: { forceBasic: boolean };
  instancing: { enabled: boolean };
  transparency: { bins: number; sortMode: string };
}

export interface RenderingAppearanceState {
  [key: string]: unknown;
}

export interface RenderingState {
  hideAllGeometry: boolean;
  appearance: RenderingAppearanceState;
  options: RenderingOptionsState;
}

export interface ToastState {
  message: string;
  ts: number;
}

export interface VisualCacheState {
  model: Record<string, unknown> | null;
  presetSun: Record<string, unknown> | null;
  presetMoon: Record<string, unknown> | null;
  sceneFlagsModel: boolean[] | null;
  sceneFlagsPresetSun: boolean[] | null;
  sceneFlagsPresetMoon: boolean[] | null;
  lightActiveModel: number[] | null;
  lightActivePresetSun: number[] | null;
  lightActivePresetMoon: number[] | null;
  appearanceModel: Record<string, unknown> | null;
  appearancePresetSun: Record<string, unknown> | null;
  appearancePresetMoon: Record<string, unknown> | null;
}

export interface ViewerState {
  overlays: OverlayState;
  runtime: RuntimeState;
  theme: ThemeState;
  visualSourceMode: 'model' | 'preset-sun' | 'preset-moon';
  visualBackups: VisualCacheState;
  visualBaselines: VisualCacheState;
  panels: PanelState;
  shell: ShellState;
  rendering: RenderingState;
  toast: ToastState | null;
}

export interface UiControl {
  item_id: string;
  type: string;
  label?: string;
  name?: string;
  binding?: string;
  options?: string[] | string;
  default?: unknown;
  shortcut?: string[] | null;
}

export interface ViewerStore {
  get(): ViewerState;
  replace(state: Partial<ViewerState> | ViewerState): void;
  update(mutator: (draft: ViewerState) => void): void;
  subscribe(listener: (state: ViewerState) => void): () => void;
}

export interface ViewerGroupState {
  geom?: boolean[];
  site?: boolean[];
  joint?: boolean[];
  tendon?: boolean[];
  actuator?: boolean[];
  flex?: boolean[];
  skin?: boolean[];
}

export interface AlignSnapshotState {
  seq?: number;
  center?: [number, number, number];
  radius?: number;
  camera?: Record<string, unknown> | null;
  timestamp?: number;
  source?: string;
}

export interface CopySnapshotState {
  seq?: number;
  precision?: string;
  nq?: number;
  nv?: number;
  timestamp?: number;
  qposPreview?: number[];
  qvelPreview?: number[];
  complete?: boolean;
}

export interface BackendSnapshot {
  t: number;
  rate: number;
  paused: boolean;
  ngeom: number;
  scn_ngeom?: number;
  nq?: number;
  nv?: number;
  options?: Record<string, unknown> | null;
  optionSupport?: { supported: boolean; pointers: string[] } | null;
  info?: Record<string, unknown> | null;
  contacts?: { n?: number; [key: string]: unknown } | null;
  renderAssets?: Record<string, unknown> | null;
  visual?: Record<string, unknown> | null;
  visualDefaults?: Record<string, unknown> | null;
  statistic?: Record<string, unknown> | null;
  groups?: ViewerGroupState | null;
  cameras?: Array<Record<string, unknown>> | null;
  geoms?: Array<Record<string, unknown>> | null;
  actuators?: Array<Record<string, unknown>> | null;
  jnt_names?: string[] | null;
  jnt_qposadr?: Int32Array | number[] | null;
  jnt_range?: Float64Array | number[] | null;
  qpos?: Float64Array | number[] | null;
  ctrl?: Float64Array | number[] | null;
  eq_active?: Uint8Array | number[] | null;
  eq_type?: Int32Array | number[] | null;
  eq_obj1id?: Int32Array | number[] | null;
  eq_obj2id?: Int32Array | number[] | null;
  eq_objtype?: Int32Array | number[] | null;
  eq_names?: string[] | null;
  geom_bodyid?: Int32Array | number[] | null;
  body_parentid?: Int32Array | number[] | null;
  body_jntadr?: Int32Array | number[] | null;
  body_jntnum?: Int32Array | number[] | null;
  jtype?: Int32Array | number[] | null;
  align?: AlignSnapshotState | null;
  copyState?: CopySnapshotState | null;
  history?: Record<string, unknown> | null;
  keyframes?: Record<string, unknown> | null;
  watch?: Record<string, unknown> | null;
  watchSources?: Record<string, unknown> | null;
  [key: string]: unknown;
}

export interface BackendUiApplyPayload {
  kind: 'ui';
  id: string;
  value: unknown;
  control: UiControl;
}

export interface GestureApplyPayload {
  kind: 'gesture';
  mode: string;
  phase?: string;
  pointer?: Partial<GesturePointer>;
  drag?: Partial<DragState>;
}

export type BackendApplyPayload = BackendUiApplyPayload | GestureApplyPayload;

export interface ViewerBackend {
  kind: string;
  apply(payload: BackendApplyPayload): Promise<BackendSnapshot | undefined> | BackendSnapshot | undefined;
  snapshot(): Promise<BackendSnapshot> | BackendSnapshot;
  subscribe(listener: (snapshot: BackendSnapshot) => void): () => void;
  step?(direction?: number): Promise<BackendSnapshot | undefined> | BackendSnapshot | undefined;
  setCameraIndex?(index: number): Promise<BackendSnapshot | undefined> | BackendSnapshot | undefined;
  setRunState?(run: boolean, source?: string): Promise<BackendSnapshot | undefined> | BackendSnapshot | undefined;
  setRate?(rate: number, source?: string): Promise<BackendSnapshot | undefined> | BackendSnapshot | undefined;
  setVisualState?(payload: { visual?: Record<string, unknown> | null; sceneFlags?: boolean[] | null }): Promise<BackendSnapshot | undefined> | BackendSnapshot | undefined;
  dispose?(): void;
}

export {
  applySpecAction,
  applyGesture,
  readControlValue,
  switchVisualSourceMode,
} from '../ui/viewer_actions.mjs';

export {
  DEFAULT_VIEWER_STATE,
  createViewerStore,
  mergeBackendSnapshot,
} from '../ui/state.mjs';

export { createBackend } from '../backend/backend_core.mjs';
