// Auto-generated by tools/generate_ui_artifacts.mjs. Do not edit by hand.

import { resolveHeapBuffer as resolveSharedHeapBuffer } from '../bridge/heap_views.mjs';
import { strictCatch } from './viewer_runtime.mjs';

function pointerName(prefix, pathSegments) {
  const suffix = pathSegments
    .map((segment) => segment.replace(/[^A-Za-z0-9]/g, "_"))
    .join('_');
  return `_mjwf_model_${prefix}_${suffix}_ptr`;
}

function getFieldPtr(mod, handle, prefix, pathSegments) {
  if (!mod || !(handle > 0)) return 0;
  const fnName = pointerName(prefix, pathSegments);
  const fn = typeof mod[fnName] === 'function' ? mod[fnName] : null;
  if (!fn) return 0;
  try {
    return fn.call(mod, handle) | 0;
  } catch (err) {
    strictCatch(err, 'structs:get_field_ptr');
    return 0;
  }
}

function resolveHeapBuffer(mod) {
  if (!mod) return null;
  if (mod.__heapBuffer instanceof ArrayBuffer) {
    return mod.__heapBuffer;
  }
  try {
    const mem =
      mod.wasmExports?.memory ||
      mod.asm?.memory ||
      mod.asm?.wasmMemory ||
      mod.wasmMemory;
    if (mem?.buffer instanceof ArrayBuffer) {
      mod.__heapBuffer = mem.buffer;
      return mem.buffer;
    }
  } catch (err) {
    strictCatch(err, 'structs:resolve_heap_buffer:memory');
  }
  const heaps = [mod.HEAPF64, mod.HEAPF32, mod.HEAP32, mod.HEAPU8];
  for (const view of heaps) {
    if (view?.buffer instanceof ArrayBuffer) {
      mod.__heapBuffer = view.buffer;
      return view.buffer;
    }
  }
  return null;
}

function writeTyped(mod, ptr, ArrayType, count, rawValues, { coerceInt = false } = {}) {
  const buffer = resolveHeapBuffer(mod);
  if (!buffer) return false;
  try {
    const view = new ArrayType(buffer, ptr, count);
    const values = Array.isArray(rawValues) ? rawValues : [rawValues];
    if (values.length < count) return false;
    for (let i = 0; i < count; i += 1) {
      let v = values[i];
      if (coerceInt) {
        const num = Number(v);
        if (!Number.isFinite(num)) return false;
        view[i] = num | 0;
      } else {
        const num = Number(v);
        if (!Number.isFinite(num)) return false;
        view[i] = num;
      }
    }
    return true;
  } catch (err) {
    strictCatch(err, 'structs:write_typed');
    return false;
  }
}

function readTyped(mod, ptr, ArrayType, count, { coerceInt = false } = {}) {
  const buffer = resolveHeapBuffer(mod);
  if (!buffer) return null;
  try {
    const view = new ArrayType(buffer, ptr, count);
    if (count === 1) {
      const value = view[0];
      return coerceInt ? (value | 0) : Number(value);
    }
    return Array.from(view, (value) => (coerceInt ? (value | 0) : Number(value)));
  } catch (err) {
    strictCatch(err, 'structs:read_typed');
    return null;
  }
}

function toArrayValue(raw, size, { coerceInt = false } = {}) {
  if (Array.isArray(raw)) {
    const arr = raw.map((entry) => Number(entry));
    if (!arr.every((entry) => Number.isFinite(entry))) return null;
    if (size && arr.length < size) return null;
    return arr.slice(0, size);
  }
  const num = Number(raw);
  if (!Number.isFinite(num)) return null;
  if (!size || size === 1) return [coerceInt ? (num | 0) : num];
  return Array(size).fill(coerceInt ? (num | 0) : num);
}

export function setStructPath(target, pathSegments, value) {
  if (!target || !Array.isArray(pathSegments) || !pathSegments.length) return;
  let cursor = target;
  for (let i = 0; i < pathSegments.length; i += 1) {
    const segment = pathSegments[i];
    const match = segment.match(/^(.*)\[(\d+)\]$/);
    const key = match ? match[1] : segment;
    const hasIndex = !!match;
    const index = hasIndex ? Number(match[2]) : -1;
    if (i === pathSegments.length - 1) {
      if (hasIndex) {
        cursor[key] = Array.isArray(cursor[key]) ? cursor[key] : [];
        cursor[key][index] = value;
      } else {
        cursor[key] = value;
      }
      return;
    }
    if (hasIndex) {
      cursor[key] = Array.isArray(cursor[key]) ? cursor[key] : [];
      cursor[key][index] = cursor[key][index] || {};
      cursor = cursor[key][index];
    } else {
      cursor[key] = cursor[key] || {};
      cursor = cursor[key];
    }
  }
}

function selectArrayConfig(prefix, kind) {
  if (kind === 'int' || kind === 'enum' || kind === 'bool') {
    return { arrayType: Int32Array, coerceInt: true };
  }
  if (prefix === 'vis') {
    return { arrayType: Float32Array, coerceInt: false };
  }
  return { arrayType: Float64Array, coerceInt: false };
}

export function writeStructField(mod, handle, prefix, pathSegments, kind, size, rawValue) {
  const ptr = getFieldPtr(mod, handle, prefix, pathSegments);
  if (!ptr) return false;
  const count = Math.max(1, Number(size) || 1);
  const { arrayType, coerceInt } = selectArrayConfig(prefix, kind);
  switch (kind) {
    case 'float':
    case 'float_vec': {
      const values = toArrayValue(rawValue, count, { coerceInt });
      if (!values) return false;
      return writeTyped(mod, ptr, arrayType, count, values, { coerceInt });
    }
    case 'int':
    case 'enum': {
      const values = toArrayValue(rawValue, count, { coerceInt: true });
      if (!values) return false;
      return writeTyped(mod, ptr, Int32Array, count, values, { coerceInt: true });
    }
    case 'bool': {
      const values = toArrayValue(rawValue, count, { coerceInt: true });
      if (!values) return false;
      return writeTyped(mod, ptr, Int32Array, count, values, { coerceInt: true });
    }
    default:
      return false;
  }
}

function normaliseReadValue(kind, count, raw) {
  if (raw == null) return null;
  if (count === 1) {
    if (kind === 'bool') return raw ? 1 : 0;
    return raw;
  }
  return Array.isArray(raw) ? raw.slice(0, count) : [raw];
}

export function readStructSnapshot(mod, handle, prefix, descriptors) {
  if (!mod || !(handle > 0)) return null;
  const out = {};
  for (const descriptor of descriptors) {
    const { path, kind, size } = descriptor;
    const ptr = getFieldPtr(mod, handle, prefix, path);
    if (!ptr) continue;
    const count = Math.max(1, Number(size) || 1);
    let raw = null;
    const { arrayType, coerceInt } = selectArrayConfig(prefix, kind);
    switch (kind) {
      case 'float':
      case 'float_vec':
        raw = readTyped(mod, ptr, arrayType, count, { coerceInt });
        break;
      case 'int':
      case 'enum':
      case 'bool':
        raw = readTyped(mod, ptr, Int32Array, count, { coerceInt: true });
        break;
      default:
        break;
    }
    const value = normaliseReadValue(kind, count, raw);
    if (value != null) {
      setStructPath(out, path, value);
    }
  }
  return out;
}
export const OPTION_LAYOUT = {
  "ccd_iterations": {
    "type": "i32",
    "count": 1
  },
  "ccd_tolerance": {
    "type": "f64",
    "count": 1
  },
  "cone": {
    "type": "i32",
    "count": 1
  },
  "density": {
    "type": "f64",
    "count": 1
  },
  "disableactuator": {
    "type": "i32",
    "count": 1
  },
  "disableflags": {
    "type": "i32",
    "count": 1
  },
  "enableflags": {
    "type": "i32",
    "count": 1
  },
  "gravity": {
    "type": "f64",
    "count": 3
  },
  "impratio": {
    "type": "f64",
    "count": 1
  },
  "integrator": {
    "type": "i32",
    "count": 1
  },
  "iterations": {
    "type": "i32",
    "count": 1
  },
  "jacobian": {
    "type": "i32",
    "count": 1
  },
  "ls_iterations": {
    "type": "i32",
    "count": 1
  },
  "ls_tolerance": {
    "type": "f64",
    "count": 1
  },
  "magnetic": {
    "type": "f64",
    "count": 3
  },
  "noslip_iterations": {
    "type": "i32",
    "count": 1
  },
  "noslip_tolerance": {
    "type": "f64",
    "count": 1
  },
  "o_friction": {
    "type": "f64",
    "count": 5
  },
  "o_margin": {
    "type": "f64",
    "count": 1
  },
  "o_solimp": {
    "type": "f64",
    "count": 5
  },
  "o_solref": {
    "type": "f64",
    "count": 2
  },
  "sdf_initpoints": {
    "type": "i32",
    "count": 1
  },
  "sdf_iterations": {
    "type": "i32",
    "count": 1
  },
  "solver": {
    "type": "i32",
    "count": 1
  },
  "timestep": {
    "type": "f64",
    "count": 1
  },
  "tolerance": {
    "type": "f64",
    "count": 1
  },
  "viscosity": {
    "type": "f64",
    "count": 1
  },
  "wind": {
    "type": "f64",
    "count": 3
  }
};

const FIELD_POINTERS = {
  "ccd_iterations": "_mjwf_model_opt_ccd_iterations_ptr",
  "ccd_tolerance": "_mjwf_model_opt_ccd_tolerance_ptr",
  "cone": "_mjwf_model_opt_cone_ptr",
  "density": "_mjwf_model_opt_density_ptr",
  "disableactuator": "_mjwf_model_opt_disableactuator_ptr",
  "disableflags": "_mjwf_model_opt_disableflags_ptr",
  "enableflags": "_mjwf_model_opt_enableflags_ptr",
  "gravity": "_mjwf_model_opt_gravity_ptr",
  "impratio": "_mjwf_model_opt_impratio_ptr",
  "integrator": "_mjwf_model_opt_integrator_ptr",
  "iterations": "_mjwf_model_opt_iterations_ptr",
  "jacobian": "_mjwf_model_opt_jacobian_ptr",
  "ls_iterations": "_mjwf_model_opt_ls_iterations_ptr",
  "ls_tolerance": "_mjwf_model_opt_ls_tolerance_ptr",
  "magnetic": "_mjwf_model_opt_magnetic_ptr",
  "noslip_iterations": "_mjwf_model_opt_noslip_iterations_ptr",
  "noslip_tolerance": "_mjwf_model_opt_noslip_tolerance_ptr",
  "o_friction": "_mjwf_model_opt_o_friction_ptr",
  "o_margin": "_mjwf_model_opt_o_margin_ptr",
  "o_solimp": "_mjwf_model_opt_o_solimp_ptr",
  "o_solref": "_mjwf_model_opt_o_solref_ptr",
  "sdf_initpoints": "_mjwf_model_opt_sdf_initpoints_ptr",
  "sdf_iterations": "_mjwf_model_opt_sdf_iterations_ptr",
  "solver": "_mjwf_model_opt_solver_ptr",
  "timestep": "_mjwf_model_opt_timestep_ptr",
  "tolerance": "_mjwf_model_opt_tolerance_ptr",
  "viscosity": "_mjwf_model_opt_viscosity_ptr",
  "wind": "_mjwf_model_opt_wind_ptr"
};

function resolveOptionHeapBuffer(mod) {
  return resolveSharedHeapBuffer(mod);
}

function getOptionFieldPtr(mod, handle, field) {
  if (!mod || !(handle > 0)) return 0;
  const name = FIELD_POINTERS[field];
  if (!name) return 0;
  const fn = mod[name];
  if (typeof fn !== 'function') return 0;
  try {
    return fn.call(mod, handle) | 0;
  } catch (err) {
    strictCatch(err, 'structs:get_option_field_ptr');
    return 0;
  }
}

function writeArray(mod, ptr, ArrayType, count, rawValues, coerceInt) {
  const buffer = resolveOptionHeapBuffer(mod);
  if (!buffer) return false;
  try {
    const view = new ArrayType(buffer, ptr, count);
    const values = Array.isArray(rawValues) ? rawValues : [rawValues];
    if (values.length < count) return false;
    for (let i = 0; i < count; i += 1) {
      let num = Number(values[i]);
      if (!Number.isFinite(num)) return false;
      if (coerceInt) num = num | 0;
      view[i] = num;
    }
    return true;
  } catch (err) {
    strictCatch(err, 'structs:write_array');
    return false;
  }
}

function readArray(mod, ptr, ArrayType, count, coerceInt) {
  const buffer = resolveOptionHeapBuffer(mod);
  if (!buffer) return null;
  try {
    const view = new ArrayType(buffer, ptr, count);
    if (count === 1) {
      return coerceInt ? (view[0] | 0) : Number(view[0]);
    }
    return Array.from(view, (v) => (coerceInt ? (v | 0) : Number(v)));
  } catch (err) {
    strictCatch(err, 'structs:read_array');
    return null;
  }
}

export function writeOptionField(mod, handle, path, _kind, value) {
  if (!mod || !(handle > 0)) return false;
  if (!Array.isArray(path) || path.length === 0) return false;
  const field = path[0];
  const info = OPTION_LAYOUT[field];
  if (!info) return false;
  const ptr = getOptionFieldPtr(mod, handle, field);
  if (!ptr) return false;
  const count = info.count || 1;
  const values = Array.isArray(value) ? value : [value];
  if (values.length < count) return false;
  if (info.type === 'f64') {
    return writeArray(mod, ptr, Float64Array, count, values, false);
  }
  if (info.type === 'i32') {
    return writeArray(mod, ptr, Int32Array, count, values, true);
  }
  return false;
}

export function readOptionStruct(mod, handle) {
  if (!mod || !(handle > 0)) return null;
  const buffer = resolveOptionHeapBuffer(mod);
  if (!buffer) return null;
  const result = {};
  for (const [key, info] of Object.entries(OPTION_LAYOUT)) {
    const ptr = getOptionFieldPtr(mod, handle, key);
    if (!ptr) continue;
    try {
      if (info.type === 'f64') {
        const view = new Float64Array(buffer, ptr, info.count);
        if (info.count === 1) {
          result[key] = Number(view[0]);
        } else {
          result[key] = Array.from(view, (v) => Number(v));
        }
      } else if (info.type === 'i32') {
        const view = new Int32Array(buffer, ptr, info.count);
        if (info.count === 1) {
          result[key] = view[0] | 0;
        } else {
          result[key] = Array.from(view, (v) => v | 0);
        }
      }
    } catch (err) {
      strictCatch(err, 'structs:read_option_struct:read');
    }
  }
  return Object.keys(result).length ? result : null;
}

export function detectOptionSupport(mod) {
  if (!mod) return { supported: false, pointers: [] };
  const structPtr = typeof mod._mjwf_model_opt_ptr === 'function' ? '_mjwf_model_opt_ptr' : null;
  const fieldPtrs = Object.values(FIELD_POINTERS).filter((name) => typeof mod[name] === 'function');
  const pointers = structPtr ? [structPtr, ...fieldPtrs] : fieldPtrs;
  return {
    supported: pointers.length > 0,
    pointers,
  };
}

export const VISUAL_FIELD_DESCRIPTORS = [
  {
    "path": [
      "global",
      "azimuth"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "global",
      "bvactive"
    ],
    "kind": "enum",
    "size": 1
  },
  {
    "path": [
      "global",
      "elevation"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "global",
      "ellipsoidinertia"
    ],
    "kind": "enum",
    "size": 1
  },
  {
    "path": [
      "global",
      "fovy"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "global",
      "orthographic"
    ],
    "kind": "enum",
    "size": 1
  },
  {
    "path": [
      "headlight",
      "active"
    ],
    "kind": "enum",
    "size": 1
  },
  {
    "path": [
      "headlight",
      "ambient"
    ],
    "kind": "float_vec",
    "size": 3
  },
  {
    "path": [
      "headlight",
      "diffuse"
    ],
    "kind": "float_vec",
    "size": 3
  },
  {
    "path": [
      "headlight",
      "specular"
    ],
    "kind": "float_vec",
    "size": 3
  },
  {
    "path": [
      "map",
      "alpha"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "fogend"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "fogstart"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "force"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "haze"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "shadowclip"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "shadowscale"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "stiffness"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "stiffnessrot"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "torque"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "zfar"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "map",
      "znear"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "rgba",
      "actuator"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "actuatornegative"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "actuatorpositive"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "bv"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "bvactive"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "camera"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "com"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "connect"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "constraint"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "contactforce"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "contactfriction"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "contactgap"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "contactpoint"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "contacttorque"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "crankbroken"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "fog"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "force"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "frustum"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "haze"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "inertia"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "joint"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "light"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "rangefinder"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "selectpoint"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "rgba",
      "slidercrank"
    ],
    "kind": "float_vec",
    "size": 4
  },
  {
    "path": [
      "scale",
      "actuatorlength"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "actuatorwidth"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "camera"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "com"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "connect"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "constraint"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "contactheight"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "contactwidth"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "forcewidth"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "framelength"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "framewidth"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "jointlength"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "jointwidth"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "light"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "selectpoint"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "scale",
      "slidercrank"
    ],
    "kind": "float",
    "size": 1
  }
];

export function writeVisualField(mod, handle, pathSegments, kind, value, size) {
  return writeStructField(mod, handle, 'vis', pathSegments, kind, size, value);
}

export function readVisualStruct(mod, handle) {
  return readStructSnapshot(mod, handle, 'vis', VISUAL_FIELD_DESCRIPTORS);
}

export const STAT_FIELD_DESCRIPTORS = [
  {
    "path": [
      "center"
    ],
    "kind": "float_vec",
    "size": 3
  },
  {
    "path": [
      "extent"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "meanmass"
    ],
    "kind": "float",
    "size": 1
  },
  {
    "path": [
      "meansize"
    ],
    "kind": "float",
    "size": 1
  }
];

export function writeStatisticField(mod, handle, pathSegments, kind, value, size) {
  return writeStructField(mod, handle, 'stat', pathSegments, kind, size, value);
}

export function readStatisticStruct(mod, handle) {
  return readStructSnapshot(mod, handle, 'stat', STAT_FIELD_DESCRIPTORS);
}

