// Auto-generated by tools/generate_forge_abi_snapshot.mjs. Do not edit by hand.
// Source of truth: <forgeDistRoot>/<ver>/abi/{structs_introspect_like.json,mujoco_ast.json}

export const FORGE_ABI_VERSIONS = [
  "3.3.7",
  "3.4.0",
  "3.5.0"
];

export const TYPEDEF_BYTES_BY_VER = {
  mjtByte: {
    "3.3.7": 1,
    "3.4.0": 1,
    "3.5.0": 1
  },
  mjtNum: {
    "3.3.7": 8,
    "3.4.0": 8,
    "3.5.0": 8
  },
  mjtSize: {
    "3.3.7": 8,
    "3.4.0": 8,
    "3.5.0": 8
  },
};

export const MJMODEL_TEX_ADR_INNER_TYPE_BY_VER = {
  "3.3.7": "int",
  "3.4.0": "int",
  "3.5.0": "mjtSize"
};

export const MJMODEL_TEX_ADR_ELEMENT_KIND_BY_VER = {
  "3.3.7": "i32",
  "3.4.0": "i32",
  "3.5.0": "i64"
};
