// Auto-generated by tools/generate_forge_abi_snapshot.mjs. Do not edit by hand.
// Source of truth: <forgeDistRoot>/<ver>/abi/{structs_introspect_like.json,mujoco_ast.json,functions_introspect_like.json,enums_introspect_like.json}

export const FORGE_ABI_VERSIONS = [
  "3.3.7",
  "3.4.0",
  "3.5.0",
  "3.6.0",
  "3.7.0",
  "3.8.0",
  "3.8.1",
  "3.9.0",
  "3.10.0",
  "3.11.0",
  "3.12.0",
  "3.13.0",
  "3.14.0",
  "3.15.0"
];

export const TYPEDEF_BYTES_BY_VER = {
  mjtByte: {
    "3.3.7": 1,
    "3.4.0": 1,
    "3.5.0": 1,
    "3.6.0": 1,
    "3.7.0": 1,
    "3.8.0": 1,
    "3.8.1": 1,
    "3.9.0": 1,
    "3.10.0": 1,
    "3.11.0": 1,
    "3.12.0": 1,
    "3.13.0": 1,
    "3.14.0": 1,
    "3.15.0": 1
  },
  mjtNum: {
    "3.3.7": 8,
    "3.4.0": 8,
    "3.5.0": 8,
    "3.6.0": 8,
    "3.7.0": 8,
    "3.8.0": 8,
    "3.8.1": 8,
    "3.9.0": 8,
    "3.10.0": 8,
    "3.11.0": 8,
    "3.12.0": 8,
    "3.13.0": 8,
    "3.14.0": 8,
    "3.15.0": 8
  },
  mjtSize: {
    "3.3.7": 8,
    "3.4.0": 8,
    "3.5.0": 8,
    "3.6.0": 8,
    "3.7.0": 8,
    "3.8.0": 8,
    "3.8.1": 8,
    "3.9.0": 8,
    "3.10.0": 8,
    "3.11.0": 8,
    "3.12.0": 8,
    "3.13.0": 8,
    "3.14.0": 8,
    "3.15.0": 8
  },
};

export const MJMODEL_TEX_ADR_INNER_TYPE_BY_VER = {
  "3.3.7": "int",
  "3.4.0": "int",
  "3.5.0": "mjtSize",
  "3.6.0": "mjtSize",
  "3.7.0": "mjtSize",
  "3.8.0": "mjtSize",
  "3.8.1": "mjtSize",
  "3.9.0": "mjtSize",
  "3.10.0": "mjtSize",
  "3.11.0": "mjtSize",
  "3.12.0": "mjtSize",
  "3.13.0": "mjtSize",
  "3.14.0": "mjtSize",
  "3.15.0": "mjtSize"
};

export const MJMODEL_TEX_ADR_ELEMENT_KIND_BY_VER = {
  "3.3.7": "i32",
  "3.4.0": "i32",
  "3.5.0": "i64",
  "3.6.0": "i64",
  "3.7.0": "i64",
  "3.8.0": "i64",
  "3.8.1": "i64",
  "3.9.0": "i64",
  "3.10.0": "i64",
  "3.11.0": "i64",
  "3.12.0": "i64",
  "3.13.0": "i64",
  "3.14.0": "i64",
  "3.15.0": "i64"
};

export const MJDATA_SOLVER_RECORDS_PER_ISLAND_BY_VER = {
  "3.3.7": 200,
  "3.4.0": 200,
  "3.5.0": 200,
  "3.6.0": 200,
  "3.7.0": 200,
  "3.8.0": 200,
  "3.8.1": 200,
  "3.9.0": 200,
  "3.10.0": 200,
  "3.11.0": 200,
  "3.12.0": 200,
  "3.13.0": 200,
  "3.14.0": 200,
  "3.15.0": 200
};

export const MJV_MOVE_CAMERA_HAS_SCENE_ARG_BY_VER = {
  "3.3.7": true,
  "3.4.0": true,
  "3.5.0": true,
  "3.6.0": true,
  "3.7.0": true,
  "3.8.0": true,
  "3.8.1": true,
  "3.9.0": true,
  "3.10.0": true,
  "3.11.0": false,
  "3.12.0": false,
  "3.13.0": false,
  "3.14.0": false,
  "3.15.0": false
};

export const PLAY_COMPATIBILITY_BY_VER = {
  "3.3.7": {
    "integrationState": 8191,
    "hasNactuator": false,
    "hasControlInputs": false,
    "hasResetCtrl": false,
    "hasActuatorInputName": false,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.4.0": {
    "integrationState": 8191,
    "hasNactuator": false,
    "hasControlInputs": false,
    "hasResetCtrl": false,
    "hasActuatorInputName": false,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.5.0": {
    "integrationState": 16383,
    "hasNactuator": false,
    "hasControlInputs": false,
    "hasResetCtrl": false,
    "hasActuatorInputName": false,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.6.0": {
    "integrationState": 16383,
    "hasNactuator": false,
    "hasControlInputs": false,
    "hasResetCtrl": false,
    "hasActuatorInputName": false,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.7.0": {
    "integrationState": 16383,
    "hasNactuator": false,
    "hasControlInputs": false,
    "hasResetCtrl": false,
    "hasActuatorInputName": false,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.8.0": {
    "integrationState": 16383,
    "hasNactuator": false,
    "hasControlInputs": false,
    "hasResetCtrl": false,
    "hasActuatorInputName": false,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.8.1": {
    "integrationState": 16383,
    "hasNactuator": false,
    "hasControlInputs": false,
    "hasResetCtrl": false,
    "hasActuatorInputName": false,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.9.0": {
    "integrationState": 16383,
    "hasNactuator": false,
    "hasControlInputs": false,
    "hasResetCtrl": false,
    "hasActuatorInputName": false,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.10.0": {
    "integrationState": 16383,
    "hasNactuator": false,
    "hasControlInputs": false,
    "hasResetCtrl": false,
    "hasActuatorInputName": false,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.11.0": {
    "integrationState": 16383,
    "hasNactuator": true,
    "hasControlInputs": true,
    "hasResetCtrl": true,
    "hasActuatorInputName": true,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.12.0": {
    "integrationState": 16383,
    "hasNactuator": true,
    "hasControlInputs": true,
    "hasResetCtrl": true,
    "hasActuatorInputName": true,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      }
    ]
  },
  "3.13.0": {
    "integrationState": 16383,
    "hasNactuator": true,
    "hasControlInputs": true,
    "hasResetCtrl": true,
    "hasActuatorInputName": true,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      },
      {
        "name": "mjINT_DISCRETE",
        "value": 4
      }
    ]
  },
  "3.14.0": {
    "integrationState": 16383,
    "hasNactuator": true,
    "hasControlInputs": true,
    "hasResetCtrl": true,
    "hasActuatorInputName": true,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      },
      {
        "name": "mjINT_DISCRETE",
        "value": 4
      }
    ]
  },
  "3.15.0": {
    "integrationState": 16383,
    "hasNactuator": true,
    "hasControlInputs": true,
    "hasResetCtrl": true,
    "hasActuatorInputName": true,
    "integrators": [
      {
        "name": "mjINT_EULER",
        "value": 0
      },
      {
        "name": "mjINT_RK4",
        "value": 1
      },
      {
        "name": "mjINT_IMPLICIT",
        "value": 2
      },
      {
        "name": "mjINT_IMPLICITFAST",
        "value": 3
      },
      {
        "name": "mjINT_DISCRETE",
        "value": 4
      }
    ]
  }
};
