import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Keep this generator separate from generate_ui_artifacts.mjs to avoid coupling
// the worker protocol IDL to UI schema logic. A focused script keeps serializer
// output predictable and reduces review surface for protocol changes.

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..', '..');

const specPath = path.join(repoRoot, 'protocol', 'worker_protocol.json');
const outDir = path.join(repoRoot, 'dev', 'generated');
const protocolOutPath = path.join(outDir, 'protocol.gen.mjs');
const dispatchOutPath = path.join(outDir, 'dispatch.gen.mjs');
const templateDir = path.join(repoRoot, 'dev', 'tools', 'templates');
const workerTemplatePath = path.join(templateDir, 'physics.worker.gen.mjs');
const backendTemplatePath = path.join(templateDir, 'viewer_backend.gen.mjs');
const workerOutPath = path.join(outDir, 'physics.worker.gen.mjs');
const backendOutPath = path.join(outDir, 'viewer_backend.gen.mjs');

const spec = JSON.parse(await readFile(specPath, 'utf8'));
const allowedCtors = new Set(['Float64Array', 'Float32Array', 'Int32Array', 'Uint8Array']);

function normaliseFieldList(value, label) {
  if (!Array.isArray(value)) {
    throw new Error(`${label} must be an array`);
  }
  return value.map((entry, idx) => {
    if (!entry || typeof entry !== 'object') {
      throw new Error(`${label}[${idx}] must be an object`);
    }
    const ctor = String(entry.ctor || '');
    if (!allowedCtors.has(ctor)) {
      throw new Error(`${label}[${idx}].ctor must be one of ${Array.from(allowedCtors).join(', ')}`);
    }
    if (!Array.isArray(entry.keys) || entry.keys.length === 0) {
      throw new Error(`${label}[${idx}].keys must be a non-empty array`);
    }
    const keys = entry.keys.map((key) => String(key));
    return { ctor, keys };
  });
}

function normaliseTransferFields(value, label) {
  if (!Array.isArray(value)) {
    throw new Error(`${label} must be an array`);
  }
  return value.map((key) => String(key));
}

function normaliseNameList(value, label) {
  if (!Array.isArray(value)) {
    throw new Error(`${label} must be an array`);
  }
  return value.map((entry) => String(entry));
}

function normaliseMessageSpec(list, label) {
  if (!Array.isArray(list)) {
    throw new Error(`${label} must be an array`);
  }
  return list.map((entry, idx) => {
    if (typeof entry === 'string') {
      return { name: entry, required: [], optional: [] };
    }
    if (!entry || typeof entry !== 'object') {
      throw new Error(`${label}[${idx}] must be a string or object`);
    }
    const name = String(entry.name || entry.kind || entry.cmd || '');
    if (!name) {
      throw new Error(`${label}[${idx}] missing name`);
    }
    const required = Array.isArray(entry.required) ? entry.required.map((key) => String(key)) : [];
    const optional = Array.isArray(entry.optional) ? entry.optional.map((key) => String(key)) : [];
    return { name, required, optional };
  });
}

const snapshotViewFields = normaliseFieldList(spec.snapshot_view_fields, 'snapshot_view_fields');
const geomViewFieldsOptional = normaliseFieldList(spec.geom_view_fields_optional, 'geom_view_fields_optional');
const geomViewFieldsAlways = normaliseFieldList(spec.geom_view_fields_always, 'geom_view_fields_always');
const snapshotTransferFields = normaliseTransferFields(spec.transfer_fields?.snapshot, 'transfer_fields.snapshot');
const contactTransferFields = normaliseTransferFields(spec.transfer_fields?.contacts, 'transfer_fields.contacts');
const commandSpec = normaliseMessageSpec(spec.commands, 'commands');
const eventSpec = normaliseMessageSpec(spec.events, 'events');
const commandList = commandSpec.map((entry) => entry.name);
const eventList = eventSpec.map((entry) => entry.name);

function renderFieldList(name, entries) {
  const lines = entries.map((entry) => `  [${entry.ctor}, ${JSON.stringify(entry.keys)}],`);
  return `export const ${name} = [\n${lines.join('\n')}\n];\n`;
}

function renderFieldSpec(name, entries) {
  const rows = entries.map((entry) => {
    return `  ${JSON.stringify(entry.name)}: { required: ${JSON.stringify(entry.required)}, optional: ${JSON.stringify(entry.optional)} },`;
  });
  return `export const ${name} = {\n${rows.join('\n')}\n};\n`;
}

const protocolOutput = [
  '// Auto-generated by dev/tools/generate_worker_protocol.mjs. Do not edit by hand.',
  '',
  renderFieldList('SNAPSHOT_VIEW_FIELDS', snapshotViewFields),
  renderFieldList('GEOM_VIEW_FIELDS_OPTIONAL', geomViewFieldsOptional),
  renderFieldList('GEOM_VIEW_FIELDS_ALWAYS', geomViewFieldsAlways),
  `export const WORKER_COMMANDS = ${JSON.stringify(commandList, null, 2)};\n`,
  `export const WORKER_EVENTS = ${JSON.stringify(eventList, null, 2)};\n`,
  renderFieldSpec('COMMAND_FIELDS', commandSpec),
  renderFieldSpec('EVENT_FIELDS', eventSpec),
  `export const SNAPSHOT_TRANSFER_FIELDS = ${JSON.stringify(snapshotTransferFields, null, 2)};\n`,
  `export const CONTACT_TRANSFER_FIELDS = ${JSON.stringify(contactTransferFields, null, 2)};\n`,
  `function collectBuffers(source, fields, out, seen) {`,
  `  if (!source || !Array.isArray(fields)) return;`,
  `  for (const key of fields) {`,
  `    const value = source[key];`,
  `    if (!value || !ArrayBuffer.isView(value)) continue;`,
  `    const buffer = value.buffer;`,
  `    if (!(buffer instanceof ArrayBuffer) || seen.has(buffer)) continue;`,
  `    seen.add(buffer);`,
  `    out.push(buffer);`,
  `  }`,
  `}`,
  ``,
  `export function collectSnapshotTransfers(payload) {`,
  `  const transfers = [];`,
  `  const seen = new Set();`,
  `  collectBuffers(payload, SNAPSHOT_TRANSFER_FIELDS, transfers, seen);`,
  `  if (payload?.contacts) {`,
  `    collectBuffers(payload.contacts, CONTACT_TRANSFER_FIELDS, transfers, seen);`,
  `  }`,
  `  return transfers;`,
  `}`,
  '',
].join('\n');

const dispatchOutput = [
  '// Auto-generated by dev/tools/generate_worker_protocol.mjs. Do not edit by hand.',
  '',
  "import { WORKER_COMMANDS, WORKER_EVENTS, COMMAND_FIELDS, EVENT_FIELDS } from './protocol.gen.mjs';",
  '',
  'const COMMAND_SET = new Set(WORKER_COMMANDS);',
  'const EVENT_SET = new Set(WORKER_EVENTS);',
  '',
  'function assertPayloadFields(label, payload, required) {',
  '  if (!required || !required.length) return;',
  '  const missing = [];',
  '  for (const key of required) {',
  '    if (!Object.prototype.hasOwnProperty.call(payload, key)) missing.push(key);',
  '  }',
  '  if (missing.length) {',
  '    throw new Error(`${label} missing fields: ${missing.join(\', \')}`);',
  '  }',
  '}',
  '',
  'export function encodeCommand(cmd, payload = {}) {',
  '  if (!COMMAND_SET.has(cmd)) {',
  "    throw new Error('Unknown command: ' + cmd);",
  '  }',
  '  if (payload == null || typeof payload !== \"object\") {',
  '    return { cmd };',
  '  }',
  '  const required = COMMAND_FIELDS?.[cmd]?.required || [];',
  '  assertPayloadFields(`Command ${cmd}`, payload, required);',
  '  return { cmd, ...payload };',
  '}',
  '',
  'export function decodeCommand(message) {',
  '  if (!message || typeof message !== \"object\") {',
  '    throw new Error(\'Command message must be an object\');',
  '  }',
  '  const cmd = message.cmd;',
  '  if (typeof cmd !== \"string\" || !COMMAND_SET.has(cmd)) {',
  "    throw new Error('Unknown command: ' + String(cmd));",
  '  }',
  '  const payload = { ...message };',
  '  delete payload.cmd;',
  '  return { cmd, payload };',
  '}',
  '',
  'export function dispatchCommand(handlers, message) {',
  '  const decoded = decodeCommand(message);',
  '  const required = COMMAND_FIELDS?.[decoded.cmd]?.required || [];',
  '  assertPayloadFields(`Command ${decoded.cmd}`, decoded.payload, required);',
  '  const handler = handlers?.[decoded.cmd];',
  '  if (typeof handler !== \"function\") {',
  "    throw new Error('Unhandled command: ' + decoded.cmd);",
  '  }',
  '  return handler(decoded.payload, message);',
  '}',
  '',
  'export function encodeEvent(kind, payload = {}) {',
  '  if (!EVENT_SET.has(kind)) {',
  "    throw new Error('Unknown event: ' + kind);",
  '  }',
  '  if (payload == null || typeof payload !== \"object\") {',
  '    return { kind };',
  '  }',
  '  const required = EVENT_FIELDS?.[kind]?.required || [];',
  '  assertPayloadFields(`Event ${kind}`, payload, required);',
  '  return { kind, ...payload };',
  '}',
  '',
  'export function decodeEvent(message) {',
  '  if (!message || typeof message !== \"object\") {',
  '    throw new Error(\'Event message must be an object\');',
  '  }',
  '  const kind = message.kind;',
  '  if (typeof kind !== \"string\" || !EVENT_SET.has(kind)) {',
  "    throw new Error('Unknown event: ' + String(kind));",
  '  }',
  '  const payload = { ...message };',
  '  delete payload.kind;',
  '  return { kind, payload };',
  '}',
  '',
  'export function dispatchEvent(handlers, message) {',
  '  const decoded = decodeEvent(message);',
  '  const required = EVENT_FIELDS?.[decoded.kind]?.required || [];',
  '  assertPayloadFields(`Event ${decoded.kind}`, decoded.payload, required);',
  '  const handler = handlers?.[decoded.kind];',
  '  if (typeof handler !== \"function\") {',
  "    throw new Error('Unhandled event: ' + decoded.kind);",
  '  }',
  '  return handler(decoded.payload, message);',
  '}',
  '',
].join('\n');

await mkdir(outDir, { recursive: true });
await writeFile(protocolOutPath, protocolOutput, 'utf8');
await writeFile(dispatchOutPath, dispatchOutput, 'utf8');
const templateHeader = '// Auto-generated by dev/tools/generate_worker_protocol.mjs. Do not edit by hand.';
const workerTemplate = await readFile(workerTemplatePath, 'utf8');
const backendTemplate = await readFile(backendTemplatePath, 'utf8');
await writeFile(workerOutPath, `${templateHeader}\n\n${workerTemplate}`, 'utf8');
await writeFile(backendOutPath, `${templateHeader}\n\n${backendTemplate}`, 'utf8');
console.log(`Wrote ${protocolOutPath}`);
console.log(`Wrote ${dispatchOutPath}`);
console.log(`Wrote ${workerOutPath}`);
console.log(`Wrote ${backendOutPath}`);
